// generated by lib/utils/3.update-languages-data.mjs

export const LANG_NAMES = [
  "abap",
  "actionscript-3",
  "ada",
  "apache",
  "apex",
  "apl",
  "applescript",
  "ara",
  "asm",
  "astro",
  "awk",
  "ballerina",
  "bat",
  "batch",
  "berry",
  "be",
  "bibtex",
  "bicep",
  "blade",
  "c",
  "cadence",
  "cdc",
  "clarity",
  "clojure",
  "clj",
  "cmake",
  "cobol",
  "codeql",
  "ql",
  "coffee",
  "cpp",
  "crystal",
  "csharp",
  "c#",
  "cs",
  "css",
  "cue",
  "d",
  "dart",
  "dax",
  "diff",
  "docker",
  "dockerfile",
  "dream-maker",
  "elixir",
  "elm",
  "erb",
  "erlang",
  "erl",
  "fish",
  "fsharp",
  "f#",
  "fs",
  "gdresource",
  "gdscript",
  "gdshader",
  "gherkin",
  "git-commit",
  "git-rebase",
  "glsl",
  "gnuplot",
  "go",
  "graphql",
  "groovy",
  "hack",
  "haml",
  "handlebars",
  "hbs",
  "haskell",
  "hs",
  "hcl",
  "hlsl",
  "html",
  "http",
  "imba",
  "ini",
  "properties",
  "java",
  "javascript",
  "js",
  "jinja-html",
  "jison",
  "json",
  "json5",
  "jsonc",
  "jsonnet",
  "jssm",
  "fsl",
  "jsx",
  "julia",
  "kotlin",
  "kusto",
  "kql",
  "latex",
  "less",
  "liquid",
  "lisp",
  "logo",
  "lua",
  "make",
  "makefile",
  "markdown",
  "md",
  "marko",
  "matlab",
  "mdx",
  "mermaid",
  "nginx",
  "nim",
  "nix",
  "objective-c",
  "objc",
  "objective-cpp",
  "ocaml",
  "pascal",
  "perl",
  "php",
  "plsql",
  "postcss",
  "powerquery",
  "powershell",
  "ps",
  "ps1",
  "prisma",
  "prolog",
  "proto",
  "pug",
  "jade",
  "puppet",
  "purescript",
  "python",
  "py",
  "r",
  "raku",
  "perl6",
  "razor",
  "reg",
  "rel",
  "riscv",
  "rst",
  "ruby",
  "rb",
  "rust",
  "rs",
  "sas",
  "sass",
  "scala",
  "scheme",
  "scss",
  "shaderlab",
  "shader",
  "shellscript",
  "bash",
  "console",
  "sh",
  "shell",
  "zsh",
  "smalltalk",
  "solidity",
  "sparql",
  "sql",
  "ssh-config",
  "stata",
  "stylus",
  "styl",
  "svelte",
  "swift",
  "system-verilog",
  "tasl",
  "tcl",
  "tex",
  "toml",
  "tsx",
  "turtle",
  "twig",
  "typescript",
  "ts",
  "v",
  "vb",
  "cmd",
  "verilog",
  "vhdl",
  "viml",
  "vim",
  "vimscript",
  "vue-html",
  "vue",
  "wasm",
  "wenyan",
  "文言",
  "wgsl",
  "xml",
  "xsl",
  "yaml",
  "yml",
  "zenscript"
];
type NamesTuple = typeof LANG_NAMES;
export type LanguageAlias = NamesTuple[number];
export type LanguageName = 
  | "abap"
  | "actionscript-3"
  | "ada"
  | "apache"
  | "apex"
  | "apl"
  | "applescript"
  | "ara"
  | "asm"
  | "astro"
  | "awk"
  | "ballerina"
  | "bat"
  | "berry"
  | "bibtex"
  | "bicep"
  | "blade"
  | "c"
  | "cadence"
  | "clarity"
  | "clojure"
  | "cmake"
  | "cobol"
  | "codeql"
  | "coffee"
  | "cpp"
  | "crystal"
  | "csharp"
  | "css"
  | "cue"
  | "d"
  | "dart"
  | "dax"
  | "diff"
  | "docker"
  | "dream-maker"
  | "elixir"
  | "elm"
  | "erb"
  | "erlang"
  | "fish"
  | "fsharp"
  | "gdresource"
  | "gdscript"
  | "gdshader"
  | "gherkin"
  | "git-commit"
  | "git-rebase"
  | "glsl"
  | "gnuplot"
  | "go"
  | "graphql"
  | "groovy"
  | "hack"
  | "haml"
  | "handlebars"
  | "haskell"
  | "hcl"
  | "hlsl"
  | "html"
  | "http"
  | "imba"
  | "ini"
  | "java"
  | "javascript"
  | "jinja-html"
  | "jison"
  | "json"
  | "json5"
  | "jsonc"
  | "jsonnet"
  | "jssm"
  | "jsx"
  | "julia"
  | "kotlin"
  | "kusto"
  | "latex"
  | "less"
  | "liquid"
  | "lisp"
  | "logo"
  | "lua"
  | "make"
  | "markdown"
  | "marko"
  | "matlab"
  | "mdx"
  | "mermaid"
  | "nginx"
  | "nim"
  | "nix"
  | "objective-c"
  | "objective-cpp"
  | "ocaml"
  | "pascal"
  | "perl"
  | "php"
  | "plsql"
  | "postcss"
  | "powerquery"
  | "powershell"
  | "prisma"
  | "prolog"
  | "proto"
  | "pug"
  | "puppet"
  | "purescript"
  | "python"
  | "r"
  | "raku"
  | "razor"
  | "reg"
  | "rel"
  | "riscv"
  | "rst"
  | "ruby"
  | "rust"
  | "sas"
  | "sass"
  | "scala"
  | "scheme"
  | "scss"
  | "shaderlab"
  | "shellscript"
  | "smalltalk"
  | "solidity"
  | "sparql"
  | "sql"
  | "ssh-config"
  | "stata"
  | "stylus"
  | "svelte"
  | "swift"
  | "system-verilog"
  | "tasl"
  | "tcl"
  | "tex"
  | "toml"
  | "tsx"
  | "turtle"
  | "twig"
  | "typescript"
  | "v"
  | "vb"
  | "verilog"
  | "vhdl"
  | "viml"
  | "vue-html"
  | "vue"
  | "wasm"
  | "wenyan"
  | "wgsl"
  | "xml"
  | "xsl"
  | "yaml"
  | "zenscript";
export type ScopeName = 
  | "source.abap"
  | "source.actionscript.3"
  | "source.ada"
  | "source.apacheconf"
  | "source.apex"
  | "source.apl"
  | "source.applescript"
  | "source.ara"
  | "source.asm.x86_64"
  | "source.astro"
  | "source.awk"
  | "source.ballerina"
  | "source.batchfile"
  | "source.berry"
  | "text.bibtex"
  | "source.bicep"
  | "text.html.php.blade"
  | "source.c"
  | "source.cadence"
  | "source.clar"
  | "source.clojure"
  | "source.cmake"
  | "source.cobol"
  | "source.ql"
  | "source.coffee"
  | "source.cpp"
  | "source.crystal"
  | "source.cs"
  | "source.css"
  | "source.cue"
  | "source.d"
  | "source.dart"
  | "source.dax"
  | "source.diff"
  | "source.dockerfile"
  | "source.dm"
  | "source.elixir"
  | "source.elm"
  | "text.html.erb"
  | "source.erlang"
  | "source.fish"
  | "source.fsharp"
  | "source.gdresource"
  | "source.gdscript"
  | "source.gdshader"
  | "text.gherkin.feature"
  | "text.git-commit"
  | "text.git-rebase"
  | "source.glsl"
  | "source.gnuplot"
  | "source.go"
  | "source.graphql"
  | "source.groovy"
  | "source.hack"
  | "text.haml"
  | "text.html.handlebars"
  | "source.haskell"
  | "source.hcl"
  | "source.hlsl"
  | "text.html.basic"
  | "source.http"
  | "source.imba"
  | "source.ini"
  | "source.java"
  | "source.js"
  | "text.html.jinja"
  | "source.jison"
  | "source.json"
  | "source.json5"
  | "source.json.comments"
  | "source.jsonnet"
  | "source.jssm"
  | "source.js.jsx"
  | "source.julia"
  | "source.kotlin"
  | "source.kusto"
  | "text.tex.latex"
  | "source.css.less"
  | "text.html.liquid"
  | "source.lisp"
  | "source.logo"
  | "source.lua"
  | "source.makefile"
  | "text.html.markdown"
  | "text.marko"
  | "source.matlab"
  | "source.mdx"
  | "source.mermaid"
  | "source.nginx"
  | "source.nim"
  | "source.nix"
  | "source.objc"
  | "source.objcpp"
  | "source.ocaml"
  | "source.pascal"
  | "source.perl"
  | "source.php"
  | "source.plsql.oracle"
  | "source.css.postcss"
  | "source.powerquery"
  | "source.powershell"
  | "source.prisma"
  | "source.prolog"
  | "source.proto"
  | "text.pug"
  | "source.puppet"
  | "source.purescript"
  | "source.python"
  | "source.r"
  | "source.perl.6"
  | "text.aspnetcorerazor"
  | "source.reg"
  | "source.rel"
  | "source.riscv"
  | "source.rst"
  | "source.ruby"
  | "source.rust"
  | "source.sas"
  | "source.sass"
  | "source.scala"
  | "source.scheme"
  | "source.css.scss"
  | "source.shaderlab"
  | "source.shell"
  | "source.smalltalk"
  | "source.solidity"
  | "source.sparql"
  | "source.sql"
  | "source.ssh-config"
  | "source.stata"
  | "source.stylus"
  | "source.svelte"
  | "source.swift"
  | "source.systemverilog"
  | "source.tasl"
  | "source.tcl"
  | "text.tex"
  | "source.toml"
  | "source.tsx"
  | "source.turtle"
  | "text.html.twig"
  | "source.ts"
  | "source.v"
  | "source.asp.vb.net"
  | "source.verilog"
  | "source.vhdl"
  | "source.viml"
  | "text.html.vue-html"
  | "source.vue"
  | "source.wat"
  | "source.wenyan"
  | "source.wgsl"
  | "text.xml"
  | "text.xml.xsl"
  | "source.yaml"
  | "source.zenscript";

export type LanguageData = {
  id: LanguageName;
  path: string;
  embeddedScopes: ScopeName[];
};
  
export const aliasOrIdToScope: Record<LanguageAlias, ScopeName> = {
  "abap": "source.abap",
  "actionscript-3": "source.actionscript.3",
  "ada": "source.ada",
  "apache": "source.apacheconf",
  "apex": "source.apex",
  "apl": "source.apl",
  "applescript": "source.applescript",
  "ara": "source.ara",
  "asm": "source.asm.x86_64",
  "astro": "source.astro",
  "awk": "source.awk",
  "ballerina": "source.ballerina",
  "bat": "source.batchfile",
  "batch": "source.batchfile",
  "berry": "source.berry",
  "be": "source.berry",
  "bibtex": "text.bibtex",
  "bicep": "source.bicep",
  "blade": "text.html.php.blade",
  "c": "source.c",
  "cadence": "source.cadence",
  "cdc": "source.cadence",
  "clarity": "source.clar",
  "clojure": "source.clojure",
  "clj": "source.clojure",
  "cmake": "source.cmake",
  "cobol": "source.cobol",
  "codeql": "source.ql",
  "ql": "source.ql",
  "coffee": "source.coffee",
  "cpp": "source.cpp",
  "crystal": "source.crystal",
  "csharp": "source.cs",
  "c#": "source.cs",
  "cs": "source.cs",
  "css": "source.css",
  "cue": "source.cue",
  "d": "source.d",
  "dart": "source.dart",
  "dax": "source.dax",
  "diff": "source.diff",
  "docker": "source.dockerfile",
  "dockerfile": "source.dockerfile",
  "dream-maker": "source.dm",
  "elixir": "source.elixir",
  "elm": "source.elm",
  "erb": "text.html.erb",
  "erlang": "source.erlang",
  "erl": "source.erlang",
  "fish": "source.fish",
  "fsharp": "source.fsharp",
  "f#": "source.fsharp",
  "fs": "source.fsharp",
  "gdresource": "source.gdresource",
  "gdscript": "source.gdscript",
  "gdshader": "source.gdshader",
  "gherkin": "text.gherkin.feature",
  "git-commit": "text.git-commit",
  "git-rebase": "text.git-rebase",
  "glsl": "source.glsl",
  "gnuplot": "source.gnuplot",
  "go": "source.go",
  "graphql": "source.graphql",
  "groovy": "source.groovy",
  "hack": "source.hack",
  "haml": "text.haml",
  "handlebars": "text.html.handlebars",
  "hbs": "text.html.handlebars",
  "haskell": "source.haskell",
  "hs": "source.haskell",
  "hcl": "source.hcl",
  "hlsl": "source.hlsl",
  "html": "text.html.basic",
  "http": "source.http",
  "imba": "source.imba",
  "ini": "source.ini",
  "properties": "source.ini",
  "java": "source.java",
  "javascript": "source.js",
  "js": "source.js",
  "jinja-html": "text.html.jinja",
  "jison": "source.jison",
  "json": "source.json",
  "json5": "source.json5",
  "jsonc": "source.json.comments",
  "jsonnet": "source.jsonnet",
  "jssm": "source.jssm",
  "fsl": "source.jssm",
  "jsx": "source.js.jsx",
  "julia": "source.julia",
  "kotlin": "source.kotlin",
  "kusto": "source.kusto",
  "kql": "source.kusto",
  "latex": "text.tex.latex",
  "less": "source.css.less",
  "liquid": "text.html.liquid",
  "lisp": "source.lisp",
  "logo": "source.logo",
  "lua": "source.lua",
  "make": "source.makefile",
  "makefile": "source.makefile",
  "markdown": "text.html.markdown",
  "md": "text.html.markdown",
  "marko": "text.marko",
  "matlab": "source.matlab",
  "mdx": "source.mdx",
  "mermaid": "source.mermaid",
  "nginx": "source.nginx",
  "nim": "source.nim",
  "nix": "source.nix",
  "objective-c": "source.objc",
  "objc": "source.objc",
  "objective-cpp": "source.objcpp",
  "ocaml": "source.ocaml",
  "pascal": "source.pascal",
  "perl": "source.perl",
  "php": "source.php",
  "plsql": "source.plsql.oracle",
  "postcss": "source.css.postcss",
  "powerquery": "source.powerquery",
  "powershell": "source.powershell",
  "ps": "source.powershell",
  "ps1": "source.powershell",
  "prisma": "source.prisma",
  "prolog": "source.prolog",
  "proto": "source.proto",
  "pug": "text.pug",
  "jade": "text.pug",
  "puppet": "source.puppet",
  "purescript": "source.purescript",
  "python": "source.python",
  "py": "source.python",
  "r": "source.r",
  "raku": "source.perl.6",
  "perl6": "source.perl.6",
  "razor": "text.aspnetcorerazor",
  "reg": "source.reg",
  "rel": "source.rel",
  "riscv": "source.riscv",
  "rst": "source.rst",
  "ruby": "source.ruby",
  "rb": "source.ruby",
  "rust": "source.rust",
  "rs": "source.rust",
  "sas": "source.sas",
  "sass": "source.sass",
  "scala": "source.scala",
  "scheme": "source.scheme",
  "scss": "source.css.scss",
  "shaderlab": "source.shaderlab",
  "shader": "source.shaderlab",
  "shellscript": "source.shell",
  "bash": "source.shell",
  "console": "source.shell",
  "sh": "source.shell",
  "shell": "source.shell",
  "zsh": "source.shell",
  "smalltalk": "source.smalltalk",
  "solidity": "source.solidity",
  "sparql": "source.sparql",
  "sql": "source.sql",
  "ssh-config": "source.ssh-config",
  "stata": "source.stata",
  "stylus": "source.stylus",
  "styl": "source.stylus",
  "svelte": "source.svelte",
  "swift": "source.swift",
  "system-verilog": "source.systemverilog",
  "tasl": "source.tasl",
  "tcl": "source.tcl",
  "tex": "text.tex",
  "toml": "source.toml",
  "tsx": "source.tsx",
  "turtle": "source.turtle",
  "twig": "text.html.twig",
  "typescript": "source.ts",
  "ts": "source.ts",
  "v": "source.v",
  "vb": "source.asp.vb.net",
  "cmd": "source.asp.vb.net",
  "verilog": "source.verilog",
  "vhdl": "source.vhdl",
  "viml": "source.viml",
  "vim": "source.viml",
  "vimscript": "source.viml",
  "vue-html": "text.html.vue-html",
  "vue": "source.vue",
  "wasm": "source.wat",
  "wenyan": "source.wenyan",
  "文言": "source.wenyan",
  "wgsl": "source.wgsl",
  "xml": "text.xml",
  "xsl": "text.xml.xsl",
  "yaml": "source.yaml",
  "yml": "source.yaml",
  "zenscript": "source.zenscript"
};
export const scopeToLanguageData: Record<ScopeName, LanguageData> = {
  "source.abap": {
    "id": "abap",
    "path": "abap.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.actionscript.3": {
    "id": "actionscript-3",
    "path": "actionscript-3.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.ada": {
    "id": "ada",
    "path": "ada.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.apacheconf": {
    "id": "apache",
    "path": "apache.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.apex": {
    "id": "apex",
    "path": "apex.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.apl": {
    "id": "apl",
    "path": "apl.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "source.json",
      "source.js",
      "source.css",
      "text.xml",
      "text.html.basic"
    ]
  },
  "source.applescript": {
    "id": "applescript",
    "path": "applescript.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.ara": {
    "id": "ara",
    "path": "ara.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.asm.x86_64": {
    "id": "asm",
    "path": "asm.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.astro": {
    "id": "astro",
    "path": "astro.tmLanguage.json",
    "embeddedScopes": [
      "source.tsx",
      "source.css.postcss",
      "source.css.less",
      "source.css.scss",
      "source.css",
      "source.sass",
      "source.stylus",
      "source.ts",
      "source.js",
      "source.json"
    ]
  },
  "source.awk": {
    "id": "awk",
    "path": "awk.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.ballerina": {
    "id": "ballerina",
    "path": "ballerina.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.batchfile": {
    "id": "bat",
    "path": "bat.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.berry": {
    "id": "berry",
    "path": "berry.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.bibtex": {
    "id": "bibtex",
    "path": "bibtex.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.bicep": {
    "id": "bicep",
    "path": "bicep.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.html.php.blade": {
    "id": "blade",
    "path": "blade.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "source.css",
      "source.json",
      "source.js",
      "source.sql",
      "text.xml",
      "text.html.basic"
    ]
  },
  "source.c": {
    "id": "c",
    "path": "c.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.cadence": {
    "id": "cadence",
    "path": "cadence.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.clar": {
    "id": "clarity",
    "path": "clarity.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.clojure": {
    "id": "clojure",
    "path": "clojure.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.cmake": {
    "id": "cmake",
    "path": "cmake.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.cobol": {
    "id": "cobol",
    "path": "cobol.tmLanguage.json",
    "embeddedScopes": [
      "source.css",
      "source.js",
      "source.java",
      "text.html.basic",
      "source.sql"
    ]
  },
  "source.ql": {
    "id": "codeql",
    "path": "codeql.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "source.haskell",
      "text.tex",
      "source.stylus",
      "source.sass",
      "source.glsl",
      "text.bibtex",
      "text.tex.latex",
      "source.elixir",
      "source.erlang",
      "text.html.handlebars",
      "source.dart",
      "source.fsharp",
      "source.cs",
      "source.tsx",
      "source.ts",
      "source.shell",
      "source.scala",
      "source.rust",
      "source.julia",
      "source.python",
      "source.powershell",
      "source.perl.6",
      "source.css.scss",
      "source.swift",
      "source.objc",
      "source.css.less",
      "source.json.comments",
      "source.json",
      "source.js",
      "text.pug",
      "source.groovy",
      "source.go",
      "text.git-rebase",
      "text.git-commit",
      "source.dockerfile",
      "source.diff",
      "source.cpp",
      "source.c",
      "source.coffee",
      "source.clojure",
      "source.batchfile",
      "source.yaml",
      "text.xml.xsl",
      "text.xml",
      "source.asp.vb.net",
      "source.sql",
      "source.php",
      "source.ruby",
      "source.r",
      "source.perl",
      "source.makefile",
      "source.lua",
      "source.java",
      "source.ini",
      "text.html.basic",
      "source.css",
      "text.html.markdown"
    ]
  },
  "source.coffee": {
    "id": "coffee",
    "path": "coffee.tmLanguage.json",
    "embeddedScopes": [
      "source.js"
    ]
  },
  "source.cpp": {
    "id": "cpp",
    "path": "cpp.tmLanguage.json",
    "embeddedScopes": [
      "source.c",
      "source.sql",
      "source.glsl"
    ]
  },
  "source.crystal": {
    "id": "crystal",
    "path": "crystal.tmLanguage.json",
    "embeddedScopes": [
      "source.shell",
      "source.js",
      "source.c",
      "source.css",
      "source.sql",
      "text.html.basic"
    ]
  },
  "source.cs": {
    "id": "csharp",
    "path": "csharp.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.css": {
    "id": "css",
    "path": "css.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.cue": {
    "id": "cue",
    "path": "cue.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.d": {
    "id": "d",
    "path": "d.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.dart": {
    "id": "dart",
    "path": "dart.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.dax": {
    "id": "dax",
    "path": "dax.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.diff": {
    "id": "diff",
    "path": "diff.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.dockerfile": {
    "id": "docker",
    "path": "docker.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.dm": {
    "id": "dream-maker",
    "path": "dream-maker.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.elixir": {
    "id": "elixir",
    "path": "elixir.tmLanguage.json",
    "embeddedScopes": [
      "source.css",
      "source.js",
      "text.html.basic"
    ]
  },
  "source.elm": {
    "id": "elm",
    "path": "elm.tmLanguage.json",
    "embeddedScopes": [
      "source.c",
      "source.glsl"
    ]
  },
  "text.html.erb": {
    "id": "erb",
    "path": "erb.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "source.lua",
      "source.shell",
      "source.c",
      "source.sql",
      "text.xml",
      "source.css",
      "source.js",
      "source.ruby",
      "text.html.basic"
    ]
  },
  "source.erlang": {
    "id": "erlang",
    "path": "erlang.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.fish": {
    "id": "fish",
    "path": "fish.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.fsharp": {
    "id": "fsharp",
    "path": "fsharp.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "source.haskell",
      "text.tex",
      "source.stylus",
      "source.sass",
      "source.glsl",
      "text.bibtex",
      "text.tex.latex",
      "source.elixir",
      "source.erlang",
      "text.html.handlebars",
      "source.dart",
      "source.cs",
      "source.tsx",
      "source.ts",
      "source.shell",
      "source.scala",
      "source.rust",
      "source.julia",
      "source.python",
      "source.powershell",
      "source.perl.6",
      "source.css.scss",
      "source.swift",
      "source.objc",
      "source.css.less",
      "source.json.comments",
      "source.json",
      "source.js",
      "text.pug",
      "source.groovy",
      "source.go",
      "text.git-rebase",
      "text.git-commit",
      "source.dockerfile",
      "source.diff",
      "source.cpp",
      "source.c",
      "source.coffee",
      "source.clojure",
      "source.batchfile",
      "source.yaml",
      "text.xml.xsl",
      "text.xml",
      "source.asp.vb.net",
      "source.sql",
      "source.php",
      "source.ruby",
      "source.r",
      "source.perl",
      "source.makefile",
      "source.lua",
      "source.java",
      "source.ini",
      "text.html.basic",
      "source.css",
      "text.html.markdown"
    ]
  },
  "source.gdresource": {
    "id": "gdresource",
    "path": "gdresource.tmLanguage.json",
    "embeddedScopes": [
      "source.gdscript",
      "source.gdshader"
    ]
  },
  "source.gdscript": {
    "id": "gdscript",
    "path": "gdscript.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.gdshader": {
    "id": "gdshader",
    "path": "gdshader.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.gherkin.feature": {
    "id": "gherkin",
    "path": "gherkin.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.git-commit": {
    "id": "git-commit",
    "path": "git-commit.tmLanguage.json",
    "embeddedScopes": [
      "source.diff"
    ]
  },
  "text.git-rebase": {
    "id": "git-rebase",
    "path": "git-rebase.tmLanguage.json",
    "embeddedScopes": [
      "source.shell"
    ]
  },
  "source.glsl": {
    "id": "glsl",
    "path": "glsl.tmLanguage.json",
    "embeddedScopes": [
      "source.c"
    ]
  },
  "source.gnuplot": {
    "id": "gnuplot",
    "path": "gnuplot.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.go": {
    "id": "go",
    "path": "go.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.graphql": {
    "id": "graphql",
    "path": "graphql.tmLanguage.json",
    "embeddedScopes": [
      "source.tsx",
      "source.js.jsx",
      "source.ts",
      "source.js"
    ]
  },
  "source.groovy": {
    "id": "groovy",
    "path": "groovy.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.hack": {
    "id": "hack",
    "path": "hack.tmLanguage.json",
    "embeddedScopes": [
      "source.css",
      "source.js",
      "source.sql",
      "text.html.basic"
    ]
  },
  "text.haml": {
    "id": "haml",
    "path": "haml.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "source.haskell",
      "text.tex",
      "source.stylus",
      "source.glsl",
      "text.bibtex",
      "text.tex.latex",
      "source.elixir",
      "source.erlang",
      "text.html.handlebars",
      "source.dart",
      "source.fsharp",
      "source.cs",
      "source.tsx",
      "source.ts",
      "source.scala",
      "source.rust",
      "source.julia",
      "source.python",
      "source.powershell",
      "source.perl.6",
      "source.css.scss",
      "source.swift",
      "source.objc",
      "source.css.less",
      "source.json.comments",
      "source.json",
      "text.pug",
      "source.groovy",
      "source.go",
      "text.git-rebase",
      "text.git-commit",
      "source.dockerfile",
      "source.diff",
      "source.cpp",
      "source.clojure",
      "source.batchfile",
      "source.yaml",
      "text.xml.xsl",
      "source.asp.vb.net",
      "source.php",
      "source.r",
      "source.perl",
      "source.makefile",
      "source.java",
      "source.ini",
      "source.lua",
      "source.shell",
      "source.c",
      "source.sql",
      "text.xml",
      "text.html.basic",
      "source.css",
      "text.html.markdown",
      "source.coffee",
      "source.sass",
      "source.js",
      "source.ruby"
    ]
  },
  "text.html.handlebars": {
    "id": "handlebars",
    "path": "handlebars.tmLanguage.json",
    "embeddedScopes": [
      "source.yaml",
      "source.js",
      "source.css",
      "text.html.basic"
    ]
  },
  "source.haskell": {
    "id": "haskell",
    "path": "haskell.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.hcl": {
    "id": "hcl",
    "path": "hcl.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.hlsl": {
    "id": "hlsl",
    "path": "hlsl.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.html.basic": {
    "id": "html",
    "path": "html.tmLanguage.json",
    "embeddedScopes": [
      "source.css",
      "source.js"
    ]
  },
  "source.http": {
    "id": "http",
    "path": "http.tmLanguage.json",
    "embeddedScopes": [
      "source.tsx",
      "source.js.jsx",
      "source.ts",
      "source.js",
      "source.java",
      "source.graphql",
      "text.xml",
      "source.json",
      "source.shell"
    ]
  },
  "source.imba": {
    "id": "imba",
    "path": "imba.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.ini": {
    "id": "ini",
    "path": "ini.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.java": {
    "id": "java",
    "path": "java.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.js": {
    "id": "javascript",
    "path": "javascript.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.html.jinja": {
    "id": "jinja-html",
    "path": "jinja-html.tmLanguage.json",
    "embeddedScopes": [
      "source.css",
      "source.js",
      "text.html.basic"
    ]
  },
  "source.jison": {
    "id": "jison",
    "path": "jison.tmLanguage.json",
    "embeddedScopes": [
      "source.js"
    ]
  },
  "source.json": {
    "id": "json",
    "path": "json.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.json5": {
    "id": "json5",
    "path": "json5.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.json.comments": {
    "id": "jsonc",
    "path": "jsonc.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.jsonnet": {
    "id": "jsonnet",
    "path": "jsonnet.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.jssm": {
    "id": "jssm",
    "path": "jssm.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.js.jsx": {
    "id": "jsx",
    "path": "jsx.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.julia": {
    "id": "julia",
    "path": "julia.tmLanguage.json",
    "embeddedScopes": [
      "source.c",
      "source.glsl",
      "source.sql",
      "source.r",
      "source.js",
      "source.python",
      "source.cpp"
    ]
  },
  "source.kotlin": {
    "id": "kotlin",
    "path": "kotlin.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.kusto": {
    "id": "kusto",
    "path": "kusto.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.tex.latex": {
    "id": "latex",
    "path": "latex.tmLanguage.json",
    "embeddedScopes": [
      "source.glsl",
      "source.shell",
      "source.sql",
      "source.cpp",
      "source.c",
      "source.r",
      "source.gnuplot",
      "source.scala",
      "source.rust",
      "source.yaml",
      "source.python",
      "source.ts",
      "source.js",
      "source.ruby",
      "source.julia",
      "source.lua",
      "source.java",
      "text.xml",
      "text.html.basic",
      "source.haskell",
      "source.css",
      "text.tex"
    ]
  },
  "source.css.less": {
    "id": "less",
    "path": "less.tmLanguage.json",
    "embeddedScopes": [
      "source.css"
    ]
  },
  "text.html.liquid": {
    "id": "liquid",
    "path": "liquid.tmLanguage.json",
    "embeddedScopes": [
      "source.js",
      "source.json",
      "source.css",
      "text.html.basic"
    ]
  },
  "source.lisp": {
    "id": "lisp",
    "path": "lisp.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.logo": {
    "id": "logo",
    "path": "logo.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.lua": {
    "id": "lua",
    "path": "lua.tmLanguage.json",
    "embeddedScopes": [
      "source.c"
    ]
  },
  "source.makefile": {
    "id": "make",
    "path": "make.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.html.markdown": {
    "id": "markdown",
    "path": "markdown.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "source.haskell",
      "text.tex",
      "source.stylus",
      "source.sass",
      "source.glsl",
      "text.bibtex",
      "text.tex.latex",
      "source.elixir",
      "source.erlang",
      "text.html.handlebars",
      "source.dart",
      "source.fsharp",
      "source.cs",
      "source.tsx",
      "source.ts",
      "source.shell",
      "source.scala",
      "source.rust",
      "source.julia",
      "source.python",
      "source.powershell",
      "source.perl.6",
      "source.css.scss",
      "source.swift",
      "source.objc",
      "source.css.less",
      "source.json.comments",
      "source.json",
      "source.js",
      "text.pug",
      "source.groovy",
      "source.go",
      "text.git-rebase",
      "text.git-commit",
      "source.dockerfile",
      "source.diff",
      "source.cpp",
      "source.c",
      "source.coffee",
      "source.clojure",
      "source.batchfile",
      "source.yaml",
      "text.xml.xsl",
      "text.xml",
      "source.asp.vb.net",
      "source.sql",
      "source.php",
      "source.ruby",
      "source.r",
      "source.perl",
      "source.makefile",
      "source.lua",
      "source.java",
      "source.ini",
      "text.html.basic",
      "source.css"
    ]
  },
  "text.marko": {
    "id": "marko",
    "path": "marko.tmLanguage.json",
    "embeddedScopes": [
      "source.js",
      "source.css.scss",
      "source.css.less",
      "source.css"
    ]
  },
  "source.matlab": {
    "id": "matlab",
    "path": "matlab.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.mdx": {
    "id": "mdx",
    "path": "mdx.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "text.tex",
      "source.stylus",
      "source.sass",
      "text.bibtex",
      "text.tex.latex",
      "text.html.handlebars",
      "source.dart",
      "source.fsharp",
      "source.powershell",
      "source.perl.6",
      "source.json.comments",
      "text.pug",
      "source.groovy",
      "text.git-rebase",
      "text.git-commit",
      "source.batchfile",
      "text.xml.xsl",
      "source.asp.vb.net",
      "source.php",
      "source.js.jsx",
      "source.glsl",
      "source.ts",
      "source.swift",
      "text.xml",
      "source.sql",
      "source.shell",
      "source.css.scss",
      "source.scala",
      "source.rust",
      "source.ruby",
      "source.r",
      "source.python",
      "source.perl",
      "source.objc",
      "text.html.markdown",
      "source.makefile",
      "source.lua",
      "source.css.less",
      "source.kotlin",
      "source.julia",
      "source.json",
      "source.js",
      "source.java",
      "source.ini",
      "text.html.basic",
      "source.haskell",
      "source.graphql",
      "source.go",
      "source.erlang",
      "source.elm",
      "source.elixir",
      "source.dockerfile",
      "source.diff",
      "source.css",
      "source.cs",
      "source.cpp",
      "source.coffee",
      "source.clojure",
      "source.c",
      "source.yaml",
      "source.toml",
      "source.tsx"
    ]
  },
  "source.mermaid": {
    "id": "mermaid",
    "path": "mermaid.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.nginx": {
    "id": "nginx",
    "path": "nginx.tmLanguage.json",
    "embeddedScopes": [
      "source.c",
      "source.lua"
    ]
  },
  "source.nim": {
    "id": "nim",
    "path": "nim.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "source.haskell",
      "text.tex",
      "source.stylus",
      "source.sass",
      "text.bibtex",
      "text.tex.latex",
      "source.elixir",
      "source.erlang",
      "text.html.handlebars",
      "source.dart",
      "source.fsharp",
      "source.cs",
      "source.tsx",
      "source.ts",
      "source.shell",
      "source.scala",
      "source.rust",
      "source.julia",
      "source.python",
      "source.powershell",
      "source.perl.6",
      "source.css.scss",
      "source.swift",
      "source.objc",
      "source.css.less",
      "source.json.comments",
      "source.json",
      "text.pug",
      "source.groovy",
      "source.go",
      "text.git-rebase",
      "text.git-commit",
      "source.dockerfile",
      "source.diff",
      "source.cpp",
      "source.coffee",
      "source.clojure",
      "source.batchfile",
      "source.yaml",
      "text.xml.xsl",
      "source.asp.vb.net",
      "source.sql",
      "source.php",
      "source.ruby",
      "source.r",
      "source.perl",
      "source.makefile",
      "source.lua",
      "source.ini",
      "source.java",
      "text.html.markdown",
      "source.glsl",
      "source.css",
      "source.js",
      "text.xml",
      "text.html.basic",
      "source.c"
    ]
  },
  "source.nix": {
    "id": "nix",
    "path": "nix.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.objc": {
    "id": "objective-c",
    "path": "objective-c.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.objcpp": {
    "id": "objective-cpp",
    "path": "objective-cpp.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.ocaml": {
    "id": "ocaml",
    "path": "ocaml.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.pascal": {
    "id": "pascal",
    "path": "pascal.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.perl": {
    "id": "perl",
    "path": "perl.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "source.sql",
      "source.js",
      "source.css",
      "text.xml",
      "text.html.basic"
    ]
  },
  "source.php": {
    "id": "php",
    "path": "php.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "source.css",
      "source.json",
      "source.js",
      "source.sql",
      "text.xml",
      "text.html.basic"
    ]
  },
  "source.plsql.oracle": {
    "id": "plsql",
    "path": "plsql.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.css.postcss": {
    "id": "postcss",
    "path": "postcss.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.powerquery": {
    "id": "powerquery",
    "path": "powerquery.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.powershell": {
    "id": "powershell",
    "path": "powershell.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.prisma": {
    "id": "prisma",
    "path": "prisma.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.prolog": {
    "id": "prolog",
    "path": "prolog.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.proto": {
    "id": "proto",
    "path": "proto.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.pug": {
    "id": "pug",
    "path": "pug.tmLanguage.json",
    "embeddedScopes": [
      "text.html.basic",
      "source.coffee",
      "source.stylus",
      "source.css.scss",
      "source.sass",
      "source.css",
      "source.js"
    ]
  },
  "source.puppet": {
    "id": "puppet",
    "path": "puppet.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.purescript": {
    "id": "purescript",
    "path": "purescript.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.python": {
    "id": "python",
    "path": "python.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.r": {
    "id": "r",
    "path": "r.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.perl.6": {
    "id": "raku",
    "path": "raku.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.aspnetcorerazor": {
    "id": "razor",
    "path": "razor.tmLanguage.json",
    "embeddedScopes": [
      "source.css",
      "source.js",
      "source.cs",
      "text.html.basic"
    ]
  },
  "source.reg": {
    "id": "reg",
    "path": "reg.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.rel": {
    "id": "rel",
    "path": "rel.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.riscv": {
    "id": "riscv",
    "path": "riscv.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.rst": {
    "id": "rst",
    "path": "rst.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "source.lua",
      "source.c",
      "source.css",
      "text.xml",
      "text.html.basic",
      "source.sql",
      "source.glsl",
      "source.ruby",
      "source.cmake",
      "source.yaml",
      "source.shell",
      "source.js",
      "source.python",
      "source.cpp"
    ]
  },
  "source.ruby": {
    "id": "ruby",
    "path": "ruby.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "source.lua",
      "source.shell",
      "source.js",
      "source.c",
      "source.css",
      "source.sql",
      "text.xml",
      "text.html.basic"
    ]
  },
  "source.rust": {
    "id": "rust",
    "path": "rust.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.sas": {
    "id": "sas",
    "path": "sas.tmLanguage.json",
    "embeddedScopes": [
      "source.sql"
    ]
  },
  "source.sass": {
    "id": "sass",
    "path": "sass.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.scala": {
    "id": "scala",
    "path": "scala.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.scheme": {
    "id": "scheme",
    "path": "scheme.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.css.scss": {
    "id": "scss",
    "path": "scss.tmLanguage.json",
    "embeddedScopes": [
      "source.css"
    ]
  },
  "source.shaderlab": {
    "id": "shaderlab",
    "path": "shaderlab.tmLanguage.json",
    "embeddedScopes": [
      "source.hlsl"
    ]
  },
  "source.shell": {
    "id": "shellscript",
    "path": "shellscript.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.smalltalk": {
    "id": "smalltalk",
    "path": "smalltalk.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.solidity": {
    "id": "solidity",
    "path": "solidity.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.sparql": {
    "id": "sparql",
    "path": "sparql.tmLanguage.json",
    "embeddedScopes": [
      "source.turtle"
    ]
  },
  "source.sql": {
    "id": "sql",
    "path": "sql.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.ssh-config": {
    "id": "ssh-config",
    "path": "ssh-config.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.stata": {
    "id": "stata",
    "path": "stata.tmLanguage.json",
    "embeddedScopes": [
      "source.sql"
    ]
  },
  "source.stylus": {
    "id": "stylus",
    "path": "stylus.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.svelte": {
    "id": "svelte",
    "path": "svelte.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "source.haskell",
      "text.tex",
      "source.glsl",
      "text.bibtex",
      "text.tex.latex",
      "source.elixir",
      "source.erlang",
      "text.html.handlebars",
      "source.dart",
      "source.fsharp",
      "source.cs",
      "source.tsx",
      "source.shell",
      "source.scala",
      "source.rust",
      "source.julia",
      "source.python",
      "source.powershell",
      "source.perl.6",
      "source.swift",
      "source.objc",
      "source.json.comments",
      "source.json",
      "source.groovy",
      "source.go",
      "text.git-rebase",
      "text.git-commit",
      "source.dockerfile",
      "source.diff",
      "source.cpp",
      "source.c",
      "source.clojure",
      "source.batchfile",
      "source.yaml",
      "text.xml.xsl",
      "text.xml",
      "source.asp.vb.net",
      "source.sql",
      "source.php",
      "source.ruby",
      "source.r",
      "source.perl",
      "source.makefile",
      "source.lua",
      "source.java",
      "source.ini",
      "text.html.basic",
      "text.html.markdown",
      "text.pug",
      "source.css.postcss",
      "source.css.less",
      "source.css.scss",
      "source.css",
      "source.sass",
      "source.stylus",
      "source.coffee",
      "source.ts",
      "source.js"
    ]
  },
  "source.swift": {
    "id": "swift",
    "path": "swift.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.systemverilog": {
    "id": "system-verilog",
    "path": "system-verilog.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.tasl": {
    "id": "tasl",
    "path": "tasl.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.tcl": {
    "id": "tcl",
    "path": "tcl.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.tex": {
    "id": "tex",
    "path": "tex.tmLanguage.json",
    "embeddedScopes": [
      "source.r"
    ]
  },
  "source.toml": {
    "id": "toml",
    "path": "toml.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.tsx": {
    "id": "tsx",
    "path": "tsx.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.turtle": {
    "id": "turtle",
    "path": "turtle.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.html.twig": {
    "id": "twig",
    "path": "twig.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "source.lua",
      "source.shell",
      "source.c",
      "source.json",
      "source.sql",
      "text.xml",
      "text.html.basic",
      "source.ruby",
      "source.python",
      "source.php",
      "source.js",
      "source.css"
    ]
  },
  "source.ts": {
    "id": "typescript",
    "path": "typescript.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.v": {
    "id": "v",
    "path": "v.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.asp.vb.net": {
    "id": "vb",
    "path": "vb.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.verilog": {
    "id": "verilog",
    "path": "verilog.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.vhdl": {
    "id": "vhdl",
    "path": "vhdl.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.viml": {
    "id": "viml",
    "path": "viml.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.html.vue-html": {
    "id": "vue-html",
    "path": "vue-html.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "source.haskell",
      "text.tex",
      "source.glsl",
      "text.bibtex",
      "text.tex.latex",
      "source.elixir",
      "source.erlang",
      "text.html.handlebars",
      "source.dart",
      "source.fsharp",
      "source.cs",
      "source.shell",
      "source.scala",
      "source.rust",
      "source.julia",
      "source.python",
      "source.powershell",
      "source.perl.6",
      "source.swift",
      "source.objc",
      "source.groovy",
      "source.go",
      "text.git-rebase",
      "text.git-commit",
      "source.dockerfile",
      "source.diff",
      "source.cpp",
      "source.c",
      "source.coffee",
      "source.clojure",
      "source.batchfile",
      "text.xml.xsl",
      "text.xml",
      "source.asp.vb.net",
      "source.sql",
      "source.php",
      "source.ruby",
      "source.r",
      "source.perl",
      "source.makefile",
      "source.lua",
      "source.java",
      "source.ini",
      "source.graphql",
      "source.toml",
      "source.yaml",
      "source.json5",
      "source.json.comments",
      "source.json",
      "source.tsx",
      "source.js.jsx",
      "source.ts",
      "source.css.less",
      "source.css.scss",
      "source.css",
      "source.sass",
      "source.stylus",
      "text.pug",
      "text.html.markdown",
      "text.html.basic",
      "source.js",
      "source.vue"
    ]
  },
  "source.vue": {
    "id": "vue",
    "path": "vue.tmLanguage.json",
    "embeddedScopes": [
      "source.gnuplot",
      "source.haskell",
      "text.tex",
      "source.glsl",
      "text.bibtex",
      "text.tex.latex",
      "source.elixir",
      "source.erlang",
      "text.html.handlebars",
      "source.dart",
      "source.fsharp",
      "source.cs",
      "source.shell",
      "source.scala",
      "source.rust",
      "source.julia",
      "source.python",
      "source.powershell",
      "source.perl.6",
      "source.swift",
      "source.objc",
      "source.groovy",
      "source.go",
      "text.git-rebase",
      "text.git-commit",
      "source.dockerfile",
      "source.diff",
      "source.cpp",
      "source.c",
      "source.coffee",
      "source.clojure",
      "source.batchfile",
      "text.xml.xsl",
      "text.xml",
      "source.asp.vb.net",
      "source.sql",
      "source.php",
      "source.ruby",
      "source.r",
      "source.perl",
      "source.makefile",
      "source.lua",
      "source.java",
      "source.ini",
      "source.graphql",
      "source.toml",
      "source.yaml",
      "source.json5",
      "source.json.comments",
      "source.json",
      "source.tsx",
      "source.js.jsx",
      "source.ts",
      "source.js",
      "source.css.less",
      "source.css.scss",
      "source.css",
      "source.sass",
      "source.stylus",
      "text.pug",
      "text.html.markdown",
      "text.html.basic"
    ]
  },
  "source.wat": {
    "id": "wasm",
    "path": "wasm.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.wenyan": {
    "id": "wenyan",
    "path": "wenyan.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.wgsl": {
    "id": "wgsl",
    "path": "wgsl.tmLanguage.json",
    "embeddedScopes": []
  },
  "text.xml": {
    "id": "xml",
    "path": "xml.tmLanguage.json",
    "embeddedScopes": [
      "source.java"
    ]
  },
  "text.xml.xsl": {
    "id": "xsl",
    "path": "xsl.tmLanguage.json",
    "embeddedScopes": [
      "source.java",
      "text.xml"
    ]
  },
  "source.yaml": {
    "id": "yaml",
    "path": "yaml.tmLanguage.json",
    "embeddedScopes": []
  },
  "source.zenscript": {
    "id": "zenscript",
    "path": "zenscript.tmLanguage.json",
    "embeddedScopes": []
  }
};
