// generated by lib/utils/02.languages-data.mjs

export const LANG_NAMES = [
  "1c",
  "1c-query",
  "abap",
  "actionscript-3",
  "ada",
  "adoc",
  "angular-html",
  "angular-ts",
  "apache",
  "apex",
  "apl",
  "applescript",
  "ara",
  "asciidoc",
  "asm",
  "astro",
  "awk",
  "ballerina",
  "bash",
  "bat",
  "batch",
  "be",
  "beancount",
  "berry",
  "bibtex",
  "bicep",
  "blade",
  "bsl",
  "c",
  "c#",
  "c++",
  "cadence",
  "cairo",
  "cdc",
  "clarity",
  "clj",
  "clojure",
  "closure-templates",
  "cmake",
  "cmd",
  "cobol",
  "codeowners",
  "codeql",
  "coffee",
  "coffeescript",
  "common-lisp",
  "console",
  "coq",
  "cpp",
  "cql",
  "crystal",
  "cs",
  "csharp",
  "css",
  "csv",
  "cue",
  "cypher",
  "d",
  "dart",
  "dax",
  "desktop",
  "diff",
  "docker",
  "dockerfile",
  "dotenv",
  "dream-maker",
  "edge",
  "elisp",
  "elixir",
  "elm",
  "emacs-lisp",
  "erb",
  "erl",
  "erlang",
  "f",
  "f#",
  "f03",
  "f08",
  "f18",
  "f77",
  "f90",
  "f95",
  "fennel",
  "fish",
  "fluent",
  "for",
  "fortran-fixed-form",
  "fortran-free-form",
  "fs",
  "fsharp",
  "fsl",
  "ftl",
  "gdresource",
  "gdscript",
  "gdshader",
  "genie",
  "gherkin",
  "git-commit",
  "git-rebase",
  "gjs",
  "gleam",
  "glimmer-js",
  "glimmer-ts",
  "glsl",
  "gnuplot",
  "go",
  "gql",
  "graphql",
  "groovy",
  "gts",
  "hack",
  "haml",
  "handlebars",
  "haskell",
  "haxe",
  "hbs",
  "hcl",
  "hjson",
  "hlsl",
  "hs",
  "html",
  "html-derivative",
  "http",
  "hxml",
  "hy",
  "imba",
  "ini",
  "jade",
  "java",
  "javascript",
  "jinja",
  "jison",
  "jl",
  "js",
  "json",
  "json5",
  "jsonc",
  "jsonl",
  "jsonnet",
  "jssm",
  "jsx",
  "julia",
  "kotlin",
  "kql",
  "kt",
  "kts",
  "kusto",
  "latex",
  "lean",
  "lean4",
  "less",
  "liquid",
  "lisp",
  "lit",
  "log",
  "logo",
  "lua",
  "luau",
  "make",
  "makefile",
  "markdown",
  "marko",
  "matlab",
  "md",
  "mdc",
  "mdx",
  "mediawiki",
  "mermaid",
  "mips",
  "mipsasm",
  "mmd",
  "mojo",
  "move",
  "nar",
  "narrat",
  "nextflow",
  "nf",
  "nginx",
  "nim",
  "nix",
  "nu",
  "nushell",
  "objc",
  "objective-c",
  "objective-cpp",
  "ocaml",
  "pascal",
  "perl",
  "perl6",
  "php",
  "plsql",
  "po",
  "postcss",
  "pot",
  "potx",
  "powerquery",
  "powershell",
  "prisma",
  "prolog",
  "properties",
  "proto",
  "protobuf",
  "ps",
  "ps1",
  "pug",
  "puppet",
  "purescript",
  "py",
  "python",
  "ql",
  "qml",
  "qmldir",
  "qss",
  "r",
  "racket",
  "raku",
  "razor",
  "rb",
  "reg",
  "regex",
  "regexp",
  "rel",
  "riscv",
  "rs",
  "rst",
  "ruby",
  "rust",
  "sas",
  "sass",
  "scala",
  "scheme",
  "scss",
  "sdbl",
  "sh",
  "shader",
  "shaderlab",
  "shell",
  "shellscript",
  "shellsession",
  "smalltalk",
  "solidity",
  "soy",
  "sparql",
  "spl",
  "splunk",
  "sql",
  "ssh-config",
  "stata",
  "styl",
  "stylus",
  "svelte",
  "swift",
  "system-verilog",
  "systemd",
  "talon",
  "talonscript",
  "tasl",
  "tcl",
  "templ",
  "terminal",
  "terraform",
  "tex",
  "text",
  "tf",
  "tfvars",
  "toml",
  "ts",
  "ts-tags",
  "tsp",
  "tsv",
  "tsx",
  "turtle",
  "twig",
  "txt",
  "typ",
  "typescript",
  "typespec",
  "typst",
  "v",
  "vala",
  "vb",
  "verilog",
  "vhdl",
  "vim",
  "viml",
  "vimscript",
  "vue",
  "vue-html",
  "vy",
  "vyper",
  "wasm",
  "wenyan",
  "wgsl",
  "wiki",
  "wikitext",
  "wl",
  "wolfram",
  "xml",
  "xsl",
  "yaml",
  "yml",
  "zenscript",
  "zig",
  "zsh",
  "文言"
];
type NamesTuple = typeof LANG_NAMES;
export type LanguageAlias = NamesTuple[number];
export type LanguageName = 
  | "abap"
  | "actionscript-3"
  | "ada"
  | "angular-html"
  | "angular-ts"
  | "apache"
  | "apex"
  | "apl"
  | "applescript"
  | "ara"
  | "asciidoc"
  | "asm"
  | "astro"
  | "awk"
  | "ballerina"
  | "bat"
  | "beancount"
  | "berry"
  | "bibtex"
  | "bicep"
  | "blade"
  | "bsl"
  | "c"
  | "cadence"
  | "cairo"
  | "clarity"
  | "clojure"
  | "cmake"
  | "cobol"
  | "codeowners"
  | "codeql"
  | "coffee"
  | "common-lisp"
  | "coq"
  | "cpp"
  | "crystal"
  | "csharp"
  | "css"
  | "csv"
  | "cue"
  | "cypher"
  | "d"
  | "dart"
  | "dax"
  | "desktop"
  | "diff"
  | "docker"
  | "dotenv"
  | "dream-maker"
  | "edge"
  | "elixir"
  | "elm"
  | "emacs-lisp"
  | "erb"
  | "erlang"
  | "fennel"
  | "fish"
  | "fluent"
  | "fortran-fixed-form"
  | "fortran-free-form"
  | "fsharp"
  | "gdresource"
  | "gdscript"
  | "gdshader"
  | "genie"
  | "gherkin"
  | "git-commit"
  | "git-rebase"
  | "gleam"
  | "glimmer-js"
  | "glimmer-ts"
  | "glsl"
  | "gnuplot"
  | "go"
  | "graphql"
  | "groovy"
  | "hack"
  | "haml"
  | "handlebars"
  | "haskell"
  | "haxe"
  | "hcl"
  | "hjson"
  | "hlsl"
  | "html"
  | "html-derivative"
  | "http"
  | "hxml"
  | "hy"
  | "imba"
  | "ini"
  | "java"
  | "javascript"
  | "jinja"
  | "jison"
  | "json"
  | "json5"
  | "jsonc"
  | "jsonl"
  | "jsonnet"
  | "jssm"
  | "jsx"
  | "julia"
  | "kotlin"
  | "kusto"
  | "latex"
  | "lean"
  | "less"
  | "liquid"
  | "log"
  | "logo"
  | "lua"
  | "luau"
  | "make"
  | "markdown"
  | "marko"
  | "matlab"
  | "mdc"
  | "mdx"
  | "mermaid"
  | "mipsasm"
  | "mojo"
  | "move"
  | "narrat"
  | "nextflow"
  | "nginx"
  | "nim"
  | "nix"
  | "nushell"
  | "objective-c"
  | "objective-cpp"
  | "ocaml"
  | "pascal"
  | "perl"
  | "php"
  | "plsql"
  | "po"
  | "postcss"
  | "powerquery"
  | "powershell"
  | "prisma"
  | "prolog"
  | "proto"
  | "pug"
  | "puppet"
  | "purescript"
  | "python"
  | "qml"
  | "qmldir"
  | "qss"
  | "r"
  | "racket"
  | "raku"
  | "razor"
  | "reg"
  | "regexp"
  | "rel"
  | "riscv"
  | "rst"
  | "ruby"
  | "rust"
  | "sas"
  | "sass"
  | "scala"
  | "scheme"
  | "scss"
  | "sdbl"
  | "shaderlab"
  | "shellscript"
  | "shellsession"
  | "smalltalk"
  | "solidity"
  | "soy"
  | "sparql"
  | "splunk"
  | "sql"
  | "ssh-config"
  | "stata"
  | "stylus"
  | "svelte"
  | "swift"
  | "system-verilog"
  | "systemd"
  | "talonscript"
  | "tasl"
  | "tcl"
  | "templ"
  | "terraform"
  | "tex"
  | "toml"
  | "ts-tags"
  | "tsv"
  | "tsx"
  | "turtle"
  | "twig"
  | "txt"
  | "typescript"
  | "typespec"
  | "typst"
  | "v"
  | "vala"
  | "vb"
  | "verilog"
  | "vhdl"
  | "viml"
  | "vue"
  | "vue-html"
  | "vyper"
  | "wasm"
  | "wenyan"
  | "wgsl"
  | "wikitext"
  | "wolfram"
  | "xml"
  | "xsl"
  | "yaml"
  | "zenscript"
  | "zig";
export type ScopeName = 
  | "source.abap"
  | "source.actionscript.3"
  | "source.ada"
  | "text.html.derivative.ng"
  | "source.ts.ng"
  | "source.apacheconf"
  | "source.apex"
  | "source.apl"
  | "source.applescript"
  | "source.ara"
  | "text.asciidoc"
  | "source.asm.x86_64"
  | "source.astro"
  | "source.awk"
  | "source.ballerina"
  | "source.batchfile"
  | "text.beancount"
  | "source.berry"
  | "text.bibtex"
  | "source.bicep"
  | "text.html.php.blade"
  | "source.bsl"
  | "source.c"
  | "source.cadence"
  | "source.cairo0"
  | "source.clar"
  | "source.clojure"
  | "source.cmake"
  | "source.cobol"
  | "text.codeowners"
  | "source.ql"
  | "source.coffee"
  | "source.commonlisp"
  | "source.coq"
  | "source.cpp"
  | "source.crystal"
  | "source.cs"
  | "source.css"
  | "text.csv"
  | "source.cue"
  | "source.cypher"
  | "source.d"
  | "source.dart"
  | "source.dax"
  | "source.desktop"
  | "source.diff"
  | "source.dockerfile"
  | "source.dotenv"
  | "source.dm"
  | "text.html.edge"
  | "source.elixir"
  | "source.elm"
  | "source.emacs.lisp"
  | "text.html.erb"
  | "source.erlang"
  | "source.fnl"
  | "source.fish"
  | "source.ftl"
  | "source.fortran.fixed"
  | "source.fortran.free"
  | "source.fsharp"
  | "source.gdresource"
  | "source.gdscript"
  | "source.gdshader"
  | "source.genie"
  | "text.gherkin.feature"
  | "text.git-commit"
  | "text.git-rebase"
  | "source.gleam"
  | "source.gjs"
  | "source.gts"
  | "source.glsl"
  | "source.gnuplot"
  | "source.go"
  | "source.graphql"
  | "source.groovy"
  | "source.hack"
  | "text.haml"
  | "text.html.handlebars"
  | "source.haskell"
  | "source.hx"
  | "source.hcl"
  | "source.hjson"
  | "source.hlsl"
  | "text.html.basic"
  | "text.html.derivative"
  | "source.http"
  | "source.hxml"
  | "source.hy"
  | "source.imba"
  | "source.ini"
  | "source.java"
  | "source.js"
  | "source.jinja"
  | "source.jison"
  | "source.json"
  | "source.json5"
  | "source.json.comments"
  | "source.json.lines"
  | "source.jsonnet"
  | "source.jssm"
  | "source.js.jsx"
  | "source.julia"
  | "source.kotlin"
  | "source.kusto"
  | "text.tex.latex"
  | "source.lean4"
  | "source.css.less"
  | "text.html.liquid"
  | "text.log"
  | "source.logo"
  | "source.lua"
  | "source.luau"
  | "source.makefile"
  | "text.html.markdown"
  | "text.marko"
  | "source.matlab"
  | "text.markdown.mdc.standalone"
  | "source.mdx"
  | "markdown.mermaid.codeblock"
  | "source.mips"
  | "source.mojo"
  | "source.move"
  | "source.narrat"
  | "source.nextflow"
  | "source.nginx"
  | "source.nim"
  | "source.nix"
  | "source.nushell"
  | "source.objc"
  | "source.objcpp"
  | "source.ocaml"
  | "source.pascal"
  | "source.perl"
  | "source.php"
  | "source.plsql.oracle"
  | "source.po"
  | "source.css.postcss"
  | "source.powerquery"
  | "source.powershell"
  | "source.prisma"
  | "source.prolog"
  | "source.proto"
  | "text.pug"
  | "source.puppet"
  | "source.purescript"
  | "source.python"
  | "source.qml"
  | "source.qmldir"
  | "source.qss"
  | "source.r"
  | "source.racket"
  | "source.perl.6"
  | "text.aspnetcorerazor"
  | "source.reg"
  | "source.regexp.python"
  | "source.rel"
  | "source.riscv"
  | "source.rst"
  | "source.ruby"
  | "source.rust"
  | "source.sas"
  | "source.sass"
  | "source.scala"
  | "source.scheme"
  | "source.css.scss"
  | "source.sdbl"
  | "source.shaderlab"
  | "source.shell"
  | "text.shell-session"
  | "source.smalltalk"
  | "source.solidity"
  | "text.html.soy"
  | "source.sparql"
  | "source.splunk_search"
  | "source.sql"
  | "source.ssh-config"
  | "source.stata"
  | "source.stylus"
  | "source.svelte"
  | "source.swift"
  | "source.systemverilog"
  | "source.systemd"
  | "source.talon"
  | "source.tasl"
  | "source.tcl"
  | "source.templ"
  | "source.hcl.terraform"
  | "text.tex"
  | "source.toml"
  | "source.ts.tags"
  | "text.tsv"
  | "source.tsx"
  | "source.turtle"
  | "text.html.twig"
  | "source.txt"
  | "source.ts"
  | "source.tsp"
  | "source.typst"
  | "source.v"
  | "source.vala"
  | "source.asp.vb.net"
  | "source.verilog"
  | "source.vhdl"
  | "source.viml"
  | "source.vue"
  | "text.html.vue-html"
  | "source.vyper"
  | "source.wat"
  | "source.wenyan"
  | "source.wgsl"
  | "source.wikitext"
  | "source.wolfram"
  | "text.xml"
  | "text.xml.xsl"
  | "source.yaml"
  | "source.zenscript"
  | "source.zig";

export type LanguageData = {
  id: LanguageName;
  embeddedScopes: ScopeName[];
};
  
export const aliasOrIdToScope: Record<LanguageAlias, ScopeName> = {
  "abap": "source.abap",
  "actionscript-3": "source.actionscript.3",
  "ada": "source.ada",
  "angular-html": "text.html.derivative.ng",
  "angular-ts": "source.ts.ng",
  "apache": "source.apacheconf",
  "apex": "source.apex",
  "apl": "source.apl",
  "applescript": "source.applescript",
  "ara": "source.ara",
  "asciidoc": "text.asciidoc",
  "adoc": "text.asciidoc",
  "asm": "source.asm.x86_64",
  "astro": "source.astro",
  "awk": "source.awk",
  "ballerina": "source.ballerina",
  "bat": "source.batchfile",
  "batch": "source.batchfile",
  "beancount": "text.beancount",
  "berry": "source.berry",
  "be": "source.berry",
  "bibtex": "text.bibtex",
  "bicep": "source.bicep",
  "blade": "text.html.php.blade",
  "bsl": "source.bsl",
  "1c": "source.bsl",
  "c": "source.c",
  "cadence": "source.cadence",
  "cdc": "source.cadence",
  "cairo": "source.cairo0",
  "clarity": "source.clar",
  "clojure": "source.clojure",
  "clj": "source.clojure",
  "cmake": "source.cmake",
  "cobol": "source.cobol",
  "codeowners": "text.codeowners",
  "codeql": "source.ql",
  "ql": "source.ql",
  "coffee": "source.coffee",
  "coffeescript": "source.coffee",
  "common-lisp": "source.commonlisp",
  "lisp": "source.commonlisp",
  "coq": "source.coq",
  "cpp": "source.cpp",
  "c++": "source.cpp",
  "crystal": "source.crystal",
  "csharp": "source.cs",
  "c#": "source.cs",
  "cs": "source.cs",
  "css": "source.css",
  "csv": "text.csv",
  "cue": "source.cue",
  "cypher": "source.cypher",
  "cql": "source.cypher",
  "d": "source.d",
  "dart": "source.dart",
  "dax": "source.dax",
  "desktop": "source.desktop",
  "diff": "source.diff",
  "docker": "source.dockerfile",
  "dockerfile": "source.dockerfile",
  "dotenv": "source.dotenv",
  "dream-maker": "source.dm",
  "edge": "text.html.edge",
  "elixir": "source.elixir",
  "elm": "source.elm",
  "emacs-lisp": "source.emacs.lisp",
  "elisp": "source.emacs.lisp",
  "erb": "text.html.erb",
  "erlang": "source.erlang",
  "erl": "source.erlang",
  "fennel": "source.fnl",
  "fish": "source.fish",
  "fluent": "source.ftl",
  "ftl": "source.ftl",
  "fortran-fixed-form": "source.fortran.fixed",
  "f": "source.fortran.fixed",
  "for": "source.fortran.fixed",
  "f77": "source.fortran.fixed",
  "fortran-free-form": "source.fortran.free",
  "f90": "source.fortran.free",
  "f95": "source.fortran.free",
  "f03": "source.fortran.free",
  "f08": "source.fortran.free",
  "f18": "source.fortran.free",
  "fsharp": "source.fsharp",
  "f#": "source.fsharp",
  "fs": "source.fsharp",
  "gdresource": "source.gdresource",
  "gdscript": "source.gdscript",
  "gdshader": "source.gdshader",
  "genie": "source.genie",
  "gherkin": "text.gherkin.feature",
  "git-commit": "text.git-commit",
  "git-rebase": "text.git-rebase",
  "gleam": "source.gleam",
  "glimmer-js": "source.gjs",
  "gjs": "source.gjs",
  "glimmer-ts": "source.gts",
  "gts": "source.gts",
  "glsl": "source.glsl",
  "gnuplot": "source.gnuplot",
  "go": "source.go",
  "graphql": "source.graphql",
  "gql": "source.graphql",
  "groovy": "source.groovy",
  "hack": "source.hack",
  "haml": "text.haml",
  "handlebars": "text.html.handlebars",
  "hbs": "text.html.handlebars",
  "haskell": "source.haskell",
  "hs": "source.haskell",
  "haxe": "source.hx",
  "hcl": "source.hcl",
  "hjson": "source.hjson",
  "hlsl": "source.hlsl",
  "html": "text.html.basic",
  "html-derivative": "text.html.derivative",
  "http": "source.http",
  "hxml": "source.hxml",
  "hy": "source.hy",
  "imba": "source.imba",
  "ini": "source.ini",
  "properties": "source.ini",
  "java": "source.java",
  "javascript": "source.js",
  "js": "source.js",
  "jinja": "source.jinja",
  "jison": "source.jison",
  "json": "source.json",
  "json5": "source.json5",
  "jsonc": "source.json.comments",
  "jsonl": "source.json.lines",
  "jsonnet": "source.jsonnet",
  "jssm": "source.jssm",
  "fsl": "source.jssm",
  "jsx": "source.js.jsx",
  "julia": "source.julia",
  "jl": "source.julia",
  "kotlin": "source.kotlin",
  "kt": "source.kotlin",
  "kts": "source.kotlin",
  "kusto": "source.kusto",
  "kql": "source.kusto",
  "latex": "text.tex.latex",
  "lean": "source.lean4",
  "lean4": "source.lean4",
  "less": "source.css.less",
  "liquid": "text.html.liquid",
  "log": "text.log",
  "logo": "source.logo",
  "lua": "source.lua",
  "luau": "source.luau",
  "make": "source.makefile",
  "makefile": "source.makefile",
  "markdown": "text.html.markdown",
  "md": "text.html.markdown",
  "marko": "text.marko",
  "matlab": "source.matlab",
  "mdc": "text.markdown.mdc.standalone",
  "mdx": "source.mdx",
  "mermaid": "markdown.mermaid.codeblock",
  "mmd": "markdown.mermaid.codeblock",
  "mipsasm": "source.mips",
  "mips": "source.mips",
  "mojo": "source.mojo",
  "move": "source.move",
  "narrat": "source.narrat",
  "nar": "source.narrat",
  "nextflow": "source.nextflow",
  "nf": "source.nextflow",
  "nginx": "source.nginx",
  "nim": "source.nim",
  "nix": "source.nix",
  "nushell": "source.nushell",
  "nu": "source.nushell",
  "objective-c": "source.objc",
  "objc": "source.objc",
  "objective-cpp": "source.objcpp",
  "ocaml": "source.ocaml",
  "pascal": "source.pascal",
  "perl": "source.perl",
  "php": "source.php",
  "plsql": "source.plsql.oracle",
  "po": "source.po",
  "pot": "source.po",
  "potx": "source.po",
  "postcss": "source.css.postcss",
  "powerquery": "source.powerquery",
  "powershell": "source.powershell",
  "ps": "source.powershell",
  "ps1": "source.powershell",
  "prisma": "source.prisma",
  "prolog": "source.prolog",
  "proto": "source.proto",
  "protobuf": "source.proto",
  "pug": "text.pug",
  "jade": "text.pug",
  "puppet": "source.puppet",
  "purescript": "source.purescript",
  "python": "source.python",
  "py": "source.python",
  "qml": "source.qml",
  "qmldir": "source.qmldir",
  "qss": "source.qss",
  "r": "source.r",
  "racket": "source.racket",
  "raku": "source.perl.6",
  "perl6": "source.perl.6",
  "razor": "text.aspnetcorerazor",
  "reg": "source.reg",
  "regexp": "source.regexp.python",
  "regex": "source.regexp.python",
  "rel": "source.rel",
  "riscv": "source.riscv",
  "rst": "source.rst",
  "ruby": "source.ruby",
  "rb": "source.ruby",
  "rust": "source.rust",
  "rs": "source.rust",
  "sas": "source.sas",
  "sass": "source.sass",
  "scala": "source.scala",
  "scheme": "source.scheme",
  "scss": "source.css.scss",
  "sdbl": "source.sdbl",
  "1c-query": "source.sdbl",
  "shaderlab": "source.shaderlab",
  "shader": "source.shaderlab",
  "shellscript": "source.shell",
  "bash": "source.shell",
  "sh": "source.shell",
  "shell": "source.shell",
  "zsh": "source.shell",
  "shellsession": "text.shell-session",
  "console": "text.shell-session",
  "smalltalk": "source.smalltalk",
  "solidity": "source.solidity",
  "soy": "text.html.soy",
  "closure-templates": "text.html.soy",
  "sparql": "source.sparql",
  "splunk": "source.splunk_search",
  "spl": "source.splunk_search",
  "sql": "source.sql",
  "ssh-config": "source.ssh-config",
  "stata": "source.stata",
  "stylus": "source.stylus",
  "styl": "source.stylus",
  "svelte": "source.svelte",
  "swift": "source.swift",
  "system-verilog": "source.systemverilog",
  "systemd": "source.systemd",
  "talonscript": "source.talon",
  "talon": "source.talon",
  "tasl": "source.tasl",
  "tcl": "source.tcl",
  "templ": "source.templ",
  "terraform": "source.hcl.terraform",
  "tf": "source.hcl.terraform",
  "tfvars": "source.hcl.terraform",
  "tex": "text.tex",
  "toml": "source.toml",
  "ts-tags": "source.ts.tags",
  "lit": "source.ts.tags",
  "tsv": "text.tsv",
  "tsx": "source.tsx",
  "turtle": "source.turtle",
  "twig": "text.html.twig",
  "txt": "source.txt",
  "typescript": "source.ts",
  "ts": "source.ts",
  "typespec": "source.tsp",
  "tsp": "source.tsp",
  "typst": "source.typst",
  "typ": "source.typst",
  "v": "source.v",
  "vala": "source.vala",
  "vb": "source.asp.vb.net",
  "cmd": "source.asp.vb.net",
  "verilog": "source.verilog",
  "vhdl": "source.vhdl",
  "viml": "source.viml",
  "vim": "source.viml",
  "vimscript": "source.viml",
  "vue": "source.vue",
  "vue-html": "text.html.vue-html",
  "vyper": "source.vyper",
  "vy": "source.vyper",
  "wasm": "source.wat",
  "wenyan": "source.wenyan",
  "文言": "source.wenyan",
  "wgsl": "source.wgsl",
  "wikitext": "source.wikitext",
  "mediawiki": "source.wikitext",
  "wiki": "source.wikitext",
  "wolfram": "source.wolfram",
  "wl": "source.wolfram",
  "xml": "text.xml",
  "xsl": "text.xml.xsl",
  "yaml": "source.yaml",
  "yml": "source.yaml",
  "zenscript": "source.zenscript",
  "zig": "source.zig"
};
export const scopeToLanguageData: Record<ScopeName, LanguageData> = {
  "source.abap": {
    "id": "abap",
    "embeddedScopes": []
  },
  "source.actionscript.3": {
    "id": "actionscript-3",
    "embeddedScopes": []
  },
  "source.ada": {
    "id": "ada",
    "embeddedScopes": []
  },
  "text.html.derivative.ng": {
    "id": "angular-html",
    "embeddedScopes": [
      "text.html.basic"
    ]
  },
  "source.ts.ng": {
    "id": "angular-ts",
    "embeddedScopes": []
  },
  "source.apacheconf": {
    "id": "apache",
    "embeddedScopes": []
  },
  "source.apex": {
    "id": "apex",
    "embeddedScopes": []
  },
  "source.apl": {
    "id": "apl",
    "embeddedScopes": [
      "text.html.basic",
      "text.xml",
      "source.css",
      "source.js",
      "source.json"
    ]
  },
  "source.applescript": {
    "id": "applescript",
    "embeddedScopes": []
  },
  "source.ara": {
    "id": "ara",
    "embeddedScopes": []
  },
  "text.asciidoc": {
    "id": "asciidoc",
    "embeddedScopes": [
      "text.html.basic",
      "source.yaml",
      "text.csv",
      "source.c",
      "source.clojure",
      "source.coffee",
      "source.cpp",
      "source.css",
      "source.cs",
      "source.diff",
      "source.dockerfile",
      "source.elixir",
      "source.elm",
      "source.erlang",
      "source.go",
      "source.groovy",
      "source.haskell",
      "source.java",
      "source.js",
      "source.json",
      "source.js.jsx",
      "source.julia",
      "source.kotlin",
      "source.css.less",
      "source.makefile",
      "source.objc",
      "source.ocaml",
      "source.perl",
      "source.python",
      "source.r",
      "source.ruby",
      "source.rust",
      "source.sass",
      "source.scala",
      "source.css.scss",
      "source.shell",
      "source.sql",
      "source.swift",
      "source.toml",
      "source.ts",
      "text.xml"
    ]
  },
  "source.asm.x86_64": {
    "id": "asm",
    "embeddedScopes": []
  },
  "source.astro": {
    "id": "astro",
    "embeddedScopes": [
      "source.json",
      "source.js",
      "source.ts",
      "source.stylus",
      "source.sass",
      "source.css",
      "source.css.scss",
      "source.css.less",
      "source.css.postcss",
      "source.tsx"
    ]
  },
  "source.awk": {
    "id": "awk",
    "embeddedScopes": []
  },
  "source.ballerina": {
    "id": "ballerina",
    "embeddedScopes": []
  },
  "source.batchfile": {
    "id": "bat",
    "embeddedScopes": []
  },
  "text.beancount": {
    "id": "beancount",
    "embeddedScopes": []
  },
  "source.berry": {
    "id": "berry",
    "embeddedScopes": []
  },
  "text.bibtex": {
    "id": "bibtex",
    "embeddedScopes": []
  },
  "source.bicep": {
    "id": "bicep",
    "embeddedScopes": []
  },
  "text.html.php.blade": {
    "id": "blade",
    "embeddedScopes": [
      "text.html.basic",
      "text.xml",
      "source.sql",
      "source.js",
      "source.json",
      "source.css"
    ]
  },
  "source.bsl": {
    "id": "bsl",
    "embeddedScopes": [
      "source.sdbl"
    ]
  },
  "source.c": {
    "id": "c",
    "embeddedScopes": []
  },
  "source.cadence": {
    "id": "cadence",
    "embeddedScopes": []
  },
  "source.cairo0": {
    "id": "cairo",
    "embeddedScopes": [
      "source.python"
    ]
  },
  "source.clar": {
    "id": "clarity",
    "embeddedScopes": []
  },
  "source.clojure": {
    "id": "clojure",
    "embeddedScopes": []
  },
  "source.cmake": {
    "id": "cmake",
    "embeddedScopes": []
  },
  "source.cobol": {
    "id": "cobol",
    "embeddedScopes": [
      "text.html.basic",
      "source.java"
    ]
  },
  "text.codeowners": {
    "id": "codeowners",
    "embeddedScopes": []
  },
  "source.ql": {
    "id": "codeql",
    "embeddedScopes": []
  },
  "source.coffee": {
    "id": "coffee",
    "embeddedScopes": [
      "source.js"
    ]
  },
  "source.commonlisp": {
    "id": "common-lisp",
    "embeddedScopes": []
  },
  "source.coq": {
    "id": "coq",
    "embeddedScopes": []
  },
  "source.cpp": {
    "id": "cpp",
    "embeddedScopes": [
      "source.regexp.python",
      "source.glsl",
      "source.sql"
    ]
  },
  "source.crystal": {
    "id": "crystal",
    "embeddedScopes": [
      "text.html.basic",
      "source.sql",
      "source.css",
      "source.c",
      "source.js",
      "source.shell"
    ]
  },
  "source.cs": {
    "id": "csharp",
    "embeddedScopes": []
  },
  "source.css": {
    "id": "css",
    "embeddedScopes": []
  },
  "text.csv": {
    "id": "csv",
    "embeddedScopes": []
  },
  "source.cue": {
    "id": "cue",
    "embeddedScopes": []
  },
  "source.cypher": {
    "id": "cypher",
    "embeddedScopes": []
  },
  "source.d": {
    "id": "d",
    "embeddedScopes": []
  },
  "source.dart": {
    "id": "dart",
    "embeddedScopes": []
  },
  "source.dax": {
    "id": "dax",
    "embeddedScopes": []
  },
  "source.desktop": {
    "id": "desktop",
    "embeddedScopes": []
  },
  "source.diff": {
    "id": "diff",
    "embeddedScopes": []
  },
  "source.dockerfile": {
    "id": "docker",
    "embeddedScopes": []
  },
  "source.dotenv": {
    "id": "dotenv",
    "embeddedScopes": []
  },
  "source.dm": {
    "id": "dream-maker",
    "embeddedScopes": []
  },
  "text.html.edge": {
    "id": "edge",
    "embeddedScopes": [
      "source.ts",
      "text.html.basic",
      "text.html.derivative"
    ]
  },
  "source.elixir": {
    "id": "elixir",
    "embeddedScopes": [
      "text.html.basic"
    ]
  },
  "source.elm": {
    "id": "elm",
    "embeddedScopes": [
      "source.glsl"
    ]
  },
  "source.emacs.lisp": {
    "id": "emacs-lisp",
    "embeddedScopes": []
  },
  "text.html.erb": {
    "id": "erb",
    "embeddedScopes": [
      "text.html.basic",
      "source.ruby"
    ]
  },
  "source.erlang": {
    "id": "erlang",
    "embeddedScopes": []
  },
  "source.fnl": {
    "id": "fennel",
    "embeddedScopes": []
  },
  "source.fish": {
    "id": "fish",
    "embeddedScopes": []
  },
  "source.ftl": {
    "id": "fluent",
    "embeddedScopes": []
  },
  "source.fortran.fixed": {
    "id": "fortran-fixed-form",
    "embeddedScopes": [
      "source.fortran.free"
    ]
  },
  "source.fortran.free": {
    "id": "fortran-free-form",
    "embeddedScopes": []
  },
  "source.fsharp": {
    "id": "fsharp",
    "embeddedScopes": [
      "text.html.markdown"
    ]
  },
  "source.gdresource": {
    "id": "gdresource",
    "embeddedScopes": [
      "source.gdshader",
      "source.gdscript"
    ]
  },
  "source.gdscript": {
    "id": "gdscript",
    "embeddedScopes": []
  },
  "source.gdshader": {
    "id": "gdshader",
    "embeddedScopes": []
  },
  "source.genie": {
    "id": "genie",
    "embeddedScopes": []
  },
  "text.gherkin.feature": {
    "id": "gherkin",
    "embeddedScopes": []
  },
  "text.git-commit": {
    "id": "git-commit",
    "embeddedScopes": [
      "source.diff"
    ]
  },
  "text.git-rebase": {
    "id": "git-rebase",
    "embeddedScopes": [
      "source.shell"
    ]
  },
  "source.gleam": {
    "id": "gleam",
    "embeddedScopes": []
  },
  "source.gjs": {
    "id": "glimmer-js",
    "embeddedScopes": [
      "source.js",
      "source.ts",
      "source.css",
      "text.html.basic"
    ]
  },
  "source.gts": {
    "id": "glimmer-ts",
    "embeddedScopes": [
      "source.ts",
      "source.css",
      "source.js",
      "text.html.basic"
    ]
  },
  "source.glsl": {
    "id": "glsl",
    "embeddedScopes": [
      "source.c"
    ]
  },
  "source.gnuplot": {
    "id": "gnuplot",
    "embeddedScopes": []
  },
  "source.go": {
    "id": "go",
    "embeddedScopes": []
  },
  "source.graphql": {
    "id": "graphql",
    "embeddedScopes": [
      "source.js",
      "source.ts",
      "source.js.jsx",
      "source.tsx"
    ]
  },
  "source.groovy": {
    "id": "groovy",
    "embeddedScopes": []
  },
  "source.hack": {
    "id": "hack",
    "embeddedScopes": [
      "text.html.basic",
      "source.sql"
    ]
  },
  "text.haml": {
    "id": "haml",
    "embeddedScopes": [
      "source.ruby",
      "source.js",
      "source.sass",
      "source.coffee",
      "text.html.markdown",
      "source.css"
    ]
  },
  "text.html.handlebars": {
    "id": "handlebars",
    "embeddedScopes": [
      "text.html.basic",
      "source.css",
      "source.js",
      "source.yaml"
    ]
  },
  "source.haskell": {
    "id": "haskell",
    "embeddedScopes": []
  },
  "source.hx": {
    "id": "haxe",
    "embeddedScopes": []
  },
  "source.hcl": {
    "id": "hcl",
    "embeddedScopes": []
  },
  "source.hjson": {
    "id": "hjson",
    "embeddedScopes": []
  },
  "source.hlsl": {
    "id": "hlsl",
    "embeddedScopes": []
  },
  "text.html.basic": {
    "id": "html",
    "embeddedScopes": [
      "source.js",
      "source.css"
    ]
  },
  "text.html.derivative": {
    "id": "html-derivative",
    "embeddedScopes": [
      "text.html.basic"
    ]
  },
  "source.http": {
    "id": "http",
    "embeddedScopes": [
      "source.shell",
      "source.json",
      "text.xml",
      "source.graphql"
    ]
  },
  "source.hxml": {
    "id": "hxml",
    "embeddedScopes": [
      "source.hx"
    ]
  },
  "source.hy": {
    "id": "hy",
    "embeddedScopes": []
  },
  "source.imba": {
    "id": "imba",
    "embeddedScopes": [
      "source.ts"
    ]
  },
  "source.ini": {
    "id": "ini",
    "embeddedScopes": []
  },
  "source.java": {
    "id": "java",
    "embeddedScopes": []
  },
  "source.js": {
    "id": "javascript",
    "embeddedScopes": []
  },
  "source.jinja": {
    "id": "jinja",
    "embeddedScopes": []
  },
  "source.jison": {
    "id": "jison",
    "embeddedScopes": [
      "source.js"
    ]
  },
  "source.json": {
    "id": "json",
    "embeddedScopes": []
  },
  "source.json5": {
    "id": "json5",
    "embeddedScopes": []
  },
  "source.json.comments": {
    "id": "jsonc",
    "embeddedScopes": []
  },
  "source.json.lines": {
    "id": "jsonl",
    "embeddedScopes": []
  },
  "source.jsonnet": {
    "id": "jsonnet",
    "embeddedScopes": []
  },
  "source.jssm": {
    "id": "jssm",
    "embeddedScopes": []
  },
  "source.js.jsx": {
    "id": "jsx",
    "embeddedScopes": []
  },
  "source.julia": {
    "id": "julia",
    "embeddedScopes": [
      "source.cpp",
      "source.python",
      "source.js",
      "source.r",
      "source.sql"
    ]
  },
  "source.kotlin": {
    "id": "kotlin",
    "embeddedScopes": []
  },
  "source.kusto": {
    "id": "kusto",
    "embeddedScopes": []
  },
  "text.tex.latex": {
    "id": "latex",
    "embeddedScopes": [
      "text.tex",
      "source.shell",
      "source.css",
      "source.gnuplot",
      "source.haskell",
      "text.html.basic",
      "source.java",
      "source.julia",
      "source.js",
      "source.lua",
      "source.python",
      "source.ruby",
      "source.rust",
      "source.ts",
      "text.xml",
      "source.yaml",
      "source.scala"
    ]
  },
  "source.lean4": {
    "id": "lean",
    "embeddedScopes": []
  },
  "source.css.less": {
    "id": "less",
    "embeddedScopes": []
  },
  "text.html.liquid": {
    "id": "liquid",
    "embeddedScopes": [
      "text.html.basic",
      "source.css",
      "source.json",
      "source.js"
    ]
  },
  "text.log": {
    "id": "log",
    "embeddedScopes": []
  },
  "source.logo": {
    "id": "logo",
    "embeddedScopes": []
  },
  "source.lua": {
    "id": "lua",
    "embeddedScopes": [
      "source.c"
    ]
  },
  "source.luau": {
    "id": "luau",
    "embeddedScopes": []
  },
  "source.makefile": {
    "id": "make",
    "embeddedScopes": []
  },
  "text.html.markdown": {
    "id": "markdown",
    "embeddedScopes": [
      "source.css",
      "text.html.basic",
      "source.ini",
      "source.java",
      "source.lua",
      "source.makefile",
      "source.perl",
      "source.r",
      "source.ruby",
      "source.php",
      "source.sql",
      "source.asp.vb.net",
      "text.xml",
      "text.xml.xsl",
      "source.yaml",
      "source.batchfile",
      "source.clojure",
      "source.coffee",
      "source.c",
      "source.cpp",
      "source.diff",
      "source.dockerfile",
      "text.git-commit",
      "text.git-rebase",
      "source.go",
      "source.groovy",
      "text.pug",
      "source.js",
      "source.json",
      "source.json.comments",
      "source.css.less",
      "source.objc",
      "source.swift",
      "source.css.scss",
      "source.perl.6",
      "source.powershell",
      "source.python",
      "source.julia",
      "source.regexp.python",
      "source.rust",
      "source.scala",
      "source.shell",
      "source.ts",
      "source.tsx",
      "source.cs",
      "source.fsharp",
      "source.dart",
      "text.html.handlebars",
      "text.log",
      "source.erlang",
      "source.elixir",
      "text.tex.latex",
      "text.bibtex",
      "text.html.derivative"
    ]
  },
  "text.marko": {
    "id": "marko",
    "embeddedScopes": [
      "source.css",
      "source.css.less",
      "source.css.scss",
      "source.js"
    ]
  },
  "source.matlab": {
    "id": "matlab",
    "embeddedScopes": []
  },
  "text.markdown.mdc.standalone": {
    "id": "mdc",
    "embeddedScopes": [
      "text.html.markdown",
      "source.yaml",
      "text.html.derivative"
    ]
  },
  "source.mdx": {
    "id": "mdx",
    "embeddedScopes": [
      "source.tsx",
      "source.toml",
      "source.yaml",
      "source.c",
      "source.clojure",
      "source.coffee",
      "source.cpp",
      "source.cs",
      "source.css",
      "source.diff",
      "source.dockerfile",
      "source.elixir",
      "source.elm",
      "source.erlang",
      "source.go",
      "source.graphql",
      "source.haskell",
      "text.html.basic",
      "source.ini",
      "source.java",
      "source.js",
      "source.json",
      "source.julia",
      "source.kotlin",
      "source.css.less",
      "source.lua",
      "source.makefile",
      "text.html.markdown",
      "source.objc",
      "source.perl",
      "source.python",
      "source.r",
      "source.ruby",
      "source.rust",
      "source.scala",
      "source.css.scss",
      "source.shell",
      "text.shell-session",
      "source.sql",
      "text.xml",
      "source.swift",
      "source.ts"
    ]
  },
  "markdown.mermaid.codeblock": {
    "id": "mermaid",
    "embeddedScopes": []
  },
  "source.mips": {
    "id": "mipsasm",
    "embeddedScopes": []
  },
  "source.mojo": {
    "id": "mojo",
    "embeddedScopes": []
  },
  "source.move": {
    "id": "move",
    "embeddedScopes": []
  },
  "source.narrat": {
    "id": "narrat",
    "embeddedScopes": []
  },
  "source.nextflow": {
    "id": "nextflow",
    "embeddedScopes": []
  },
  "source.nginx": {
    "id": "nginx",
    "embeddedScopes": [
      "source.lua"
    ]
  },
  "source.nim": {
    "id": "nim",
    "embeddedScopes": [
      "source.c",
      "text.html.basic",
      "text.xml",
      "source.js",
      "source.css",
      "source.glsl",
      "text.html.markdown"
    ]
  },
  "source.nix": {
    "id": "nix",
    "embeddedScopes": []
  },
  "source.nushell": {
    "id": "nushell",
    "embeddedScopes": []
  },
  "source.objc": {
    "id": "objective-c",
    "embeddedScopes": []
  },
  "source.objcpp": {
    "id": "objective-cpp",
    "embeddedScopes": []
  },
  "source.ocaml": {
    "id": "ocaml",
    "embeddedScopes": []
  },
  "source.pascal": {
    "id": "pascal",
    "embeddedScopes": []
  },
  "source.perl": {
    "id": "perl",
    "embeddedScopes": [
      "text.html.basic",
      "text.xml",
      "source.css",
      "source.js",
      "source.sql"
    ]
  },
  "source.php": {
    "id": "php",
    "embeddedScopes": [
      "text.html.basic",
      "text.xml",
      "source.sql",
      "source.js",
      "source.json",
      "source.css"
    ]
  },
  "source.plsql.oracle": {
    "id": "plsql",
    "embeddedScopes": []
  },
  "source.po": {
    "id": "po",
    "embeddedScopes": []
  },
  "source.css.postcss": {
    "id": "postcss",
    "embeddedScopes": []
  },
  "source.powerquery": {
    "id": "powerquery",
    "embeddedScopes": []
  },
  "source.powershell": {
    "id": "powershell",
    "embeddedScopes": []
  },
  "source.prisma": {
    "id": "prisma",
    "embeddedScopes": []
  },
  "source.prolog": {
    "id": "prolog",
    "embeddedScopes": []
  },
  "source.proto": {
    "id": "proto",
    "embeddedScopes": []
  },
  "text.pug": {
    "id": "pug",
    "embeddedScopes": [
      "source.js",
      "source.css",
      "source.sass",
      "source.css.scss",
      "source.stylus",
      "source.coffee",
      "text.html.basic"
    ]
  },
  "source.puppet": {
    "id": "puppet",
    "embeddedScopes": []
  },
  "source.purescript": {
    "id": "purescript",
    "embeddedScopes": []
  },
  "source.python": {
    "id": "python",
    "embeddedScopes": []
  },
  "source.qml": {
    "id": "qml",
    "embeddedScopes": [
      "source.js"
    ]
  },
  "source.qmldir": {
    "id": "qmldir",
    "embeddedScopes": []
  },
  "source.qss": {
    "id": "qss",
    "embeddedScopes": []
  },
  "source.r": {
    "id": "r",
    "embeddedScopes": []
  },
  "source.racket": {
    "id": "racket",
    "embeddedScopes": []
  },
  "source.perl.6": {
    "id": "raku",
    "embeddedScopes": []
  },
  "text.aspnetcorerazor": {
    "id": "razor",
    "embeddedScopes": [
      "text.html.basic",
      "source.cs"
    ]
  },
  "source.reg": {
    "id": "reg",
    "embeddedScopes": []
  },
  "source.regexp.python": {
    "id": "regexp",
    "embeddedScopes": []
  },
  "source.rel": {
    "id": "rel",
    "embeddedScopes": []
  },
  "source.riscv": {
    "id": "riscv",
    "embeddedScopes": []
  },
  "source.rst": {
    "id": "rst",
    "embeddedScopes": [
      "text.html.derivative",
      "source.cpp",
      "source.python",
      "source.js",
      "source.shell",
      "source.yaml",
      "source.cmake",
      "source.ruby"
    ]
  },
  "source.ruby": {
    "id": "ruby",
    "embeddedScopes": [
      "text.html.basic",
      "text.haml",
      "text.xml",
      "source.sql",
      "source.graphql",
      "source.css",
      "source.cpp",
      "source.c",
      "source.js",
      "source.shell",
      "source.lua",
      "source.yaml"
    ]
  },
  "source.rust": {
    "id": "rust",
    "embeddedScopes": []
  },
  "source.sas": {
    "id": "sas",
    "embeddedScopes": [
      "source.sql"
    ]
  },
  "source.sass": {
    "id": "sass",
    "embeddedScopes": []
  },
  "source.scala": {
    "id": "scala",
    "embeddedScopes": []
  },
  "source.scheme": {
    "id": "scheme",
    "embeddedScopes": []
  },
  "source.css.scss": {
    "id": "scss",
    "embeddedScopes": [
      "source.css"
    ]
  },
  "source.sdbl": {
    "id": "sdbl",
    "embeddedScopes": []
  },
  "source.shaderlab": {
    "id": "shaderlab",
    "embeddedScopes": [
      "source.hlsl"
    ]
  },
  "source.shell": {
    "id": "shellscript",
    "embeddedScopes": []
  },
  "text.shell-session": {
    "id": "shellsession",
    "embeddedScopes": [
      "source.shell"
    ]
  },
  "source.smalltalk": {
    "id": "smalltalk",
    "embeddedScopes": []
  },
  "source.solidity": {
    "id": "solidity",
    "embeddedScopes": []
  },
  "text.html.soy": {
    "id": "soy",
    "embeddedScopes": [
      "text.html.basic"
    ]
  },
  "source.sparql": {
    "id": "sparql",
    "embeddedScopes": [
      "source.turtle"
    ]
  },
  "source.splunk_search": {
    "id": "splunk",
    "embeddedScopes": []
  },
  "source.sql": {
    "id": "sql",
    "embeddedScopes": []
  },
  "source.ssh-config": {
    "id": "ssh-config",
    "embeddedScopes": []
  },
  "source.stata": {
    "id": "stata",
    "embeddedScopes": [
      "source.sql"
    ]
  },
  "source.stylus": {
    "id": "stylus",
    "embeddedScopes": []
  },
  "source.svelte": {
    "id": "svelte",
    "embeddedScopes": [
      "source.js",
      "source.ts",
      "source.coffee",
      "source.stylus",
      "source.sass",
      "source.css",
      "source.css.scss",
      "source.css.less",
      "source.css.postcss",
      "text.pug",
      "text.html.markdown"
    ]
  },
  "source.swift": {
    "id": "swift",
    "embeddedScopes": []
  },
  "source.systemverilog": {
    "id": "system-verilog",
    "embeddedScopes": []
  },
  "source.systemd": {
    "id": "systemd",
    "embeddedScopes": []
  },
  "source.talon": {
    "id": "talonscript",
    "embeddedScopes": []
  },
  "source.tasl": {
    "id": "tasl",
    "embeddedScopes": []
  },
  "source.tcl": {
    "id": "tcl",
    "embeddedScopes": []
  },
  "source.templ": {
    "id": "templ",
    "embeddedScopes": [
      "source.go",
      "source.js",
      "source.css"
    ]
  },
  "source.hcl.terraform": {
    "id": "terraform",
    "embeddedScopes": []
  },
  "text.tex": {
    "id": "tex",
    "embeddedScopes": [
      "source.r"
    ]
  },
  "source.toml": {
    "id": "toml",
    "embeddedScopes": []
  },
  "source.ts.tags": {
    "id": "ts-tags",
    "embeddedScopes": [
      "source.ts"
    ]
  },
  "text.tsv": {
    "id": "tsv",
    "embeddedScopes": []
  },
  "source.tsx": {
    "id": "tsx",
    "embeddedScopes": []
  },
  "source.turtle": {
    "id": "turtle",
    "embeddedScopes": []
  },
  "text.html.twig": {
    "id": "twig",
    "embeddedScopes": [
      "source.css",
      "source.js",
      "source.css.scss",
      "source.php",
      "source.python",
      "source.ruby"
    ]
  },
  "source.txt": {
    "id": "txt",
    "embeddedScopes": []
  },
  "source.ts": {
    "id": "typescript",
    "embeddedScopes": []
  },
  "source.tsp": {
    "id": "typespec",
    "embeddedScopes": []
  },
  "source.typst": {
    "id": "typst",
    "embeddedScopes": []
  },
  "source.v": {
    "id": "v",
    "embeddedScopes": []
  },
  "source.vala": {
    "id": "vala",
    "embeddedScopes": []
  },
  "source.asp.vb.net": {
    "id": "vb",
    "embeddedScopes": []
  },
  "source.verilog": {
    "id": "verilog",
    "embeddedScopes": []
  },
  "source.vhdl": {
    "id": "vhdl",
    "embeddedScopes": []
  },
  "source.viml": {
    "id": "viml",
    "embeddedScopes": []
  },
  "source.vue": {
    "id": "vue",
    "embeddedScopes": [
      "text.html.basic",
      "text.html.markdown",
      "text.pug",
      "source.stylus",
      "source.sass",
      "source.css",
      "source.css.scss",
      "source.css.less",
      "source.js",
      "source.ts",
      "source.js.jsx",
      "source.tsx",
      "source.coffee",
      "source.json",
      "source.json.comments",
      "source.json5",
      "source.yaml",
      "source.toml",
      "source.graphql",
      "text.html.derivative"
    ]
  },
  "text.html.vue-html": {
    "id": "vue-html",
    "embeddedScopes": [
      "source.vue",
      "source.js"
    ]
  },
  "source.vyper": {
    "id": "vyper",
    "embeddedScopes": []
  },
  "source.wat": {
    "id": "wasm",
    "embeddedScopes": []
  },
  "source.wenyan": {
    "id": "wenyan",
    "embeddedScopes": []
  },
  "source.wgsl": {
    "id": "wgsl",
    "embeddedScopes": []
  },
  "source.wikitext": {
    "id": "wikitext",
    "embeddedScopes": [
      "text.html.basic",
      "source.css",
      "source.ini",
      "source.java",
      "source.lua",
      "source.makefile",
      "source.perl",
      "source.r",
      "source.ruby",
      "source.php",
      "source.sql",
      "source.asp.vb.net",
      "text.xml",
      "text.xml.xsl",
      "source.yaml",
      "source.batchfile",
      "source.clojure",
      "source.coffee",
      "source.c",
      "source.cpp",
      "source.diff",
      "source.dockerfile",
      "source.go",
      "source.groovy",
      "text.pug",
      "source.js",
      "source.json.comments",
      "source.css.less",
      "source.objc",
      "source.swift",
      "source.css.scss",
      "source.perl.6",
      "source.powershell",
      "source.python",
      "source.julia",
      "source.rust",
      "source.scala",
      "source.shell",
      "source.ts",
      "source.cs",
      "source.fsharp",
      "source.dart",
      "text.html.handlebars",
      "text.html.markdown",
      "source.erlang",
      "source.elixir",
      "text.tex.latex",
      "text.bibtex",
      "source.json"
    ]
  },
  "source.wolfram": {
    "id": "wolfram",
    "embeddedScopes": []
  },
  "text.xml": {
    "id": "xml",
    "embeddedScopes": [
      "source.java"
    ]
  },
  "text.xml.xsl": {
    "id": "xsl",
    "embeddedScopes": [
      "text.xml"
    ]
  },
  "source.yaml": {
    "id": "yaml",
    "embeddedScopes": []
  },
  "source.zenscript": {
    "id": "zenscript",
    "embeddedScopes": []
  },
  "source.zig": {
    "id": "zig",
    "embeddedScopes": []
  }
};
