// generated by lib/utils/2.update-languages.mjs
export const languages = [
  {
    "id": "abap",
    "scopeName": "source.abap",
    "path": "abap.json"
  },
  {
    "id": "actionscript-3",
    "scopeName": "source.actionscript.3",
    "path": "actionscript-3.json"
  },
  {
    "id": "ada",
    "scopeName": "source.ada",
    "path": "ada.json"
  },
  {
    "id": "angular-expression",
    "scopeName": "expression.ng",
    "path": "angular-expression.json"
  },
  {
    "id": "angular-html",
    "scopeName": "text.html.derivative.ng",
    "path": "angular-html.json",
    "embeddedLangs": [
      "html"
    ]
  },
  {
    "id": "angular-inline-style",
    "scopeName": "inline-styles.ng",
    "path": "angular-inline-style.json",
    "embeddedLangs": [
      "scss"
    ]
  },
  {
    "id": "angular-inline-template",
    "scopeName": "inline-template.ng",
    "path": "angular-inline-template.json",
    "embeddedLangs": [
      "angular-html",
      "angular-template"
    ]
  },
  {
    "id": "angular-template-blocks",
    "scopeName": "template.blocks.ng",
    "path": "angular-template-blocks.json",
    "embeddedLangs": [
      "angular-html",
      "angular-template",
      "angular-expression"
    ]
  },
  {
    "id": "angular-template",
    "scopeName": "template.ng",
    "path": "angular-template.json",
    "embeddedLangs": [
      "angular-expression"
    ]
  },
  {
    "id": "angular-ts",
    "scopeName": "source.ts.ng",
    "path": "angular-ts.json"
  },
  {
    "id": "apache",
    "scopeName": "source.apacheconf",
    "path": "apache.json"
  },
  {
    "id": "apex",
    "scopeName": "source.apex",
    "path": "apex.json"
  },
  {
    "id": "apl",
    "scopeName": "source.apl",
    "path": "apl.json",
    "embeddedLangs": [
      "html",
      "xml",
      "css",
      "javascript",
      "json"
    ]
  },
  {
    "id": "applescript",
    "scopeName": "source.applescript",
    "path": "applescript.json"
  },
  {
    "id": "ara",
    "scopeName": "source.ara",
    "path": "ara.json"
  },
  {
    "id": "asciidoc",
    "scopeName": "text.asciidoc",
    "path": "asciidoc.json",
    "embeddedLangs": [
      "yaml",
      "html",
      "c",
      "clojure",
      "coffee",
      "cpp",
      "css",
      "csharp",
      "diff",
      "docker",
      "elixir",
      "elm",
      "erlang",
      "go",
      "groovy",
      "haskell",
      "java",
      "javascript",
      "json",
      "jsx",
      "julia",
      "kotlin",
      "less",
      "make",
      "objective-c",
      "ocaml",
      "perl",
      "python",
      "r",
      "ruby",
      "rust",
      "sass",
      "scala",
      "scss",
      "shellscript",
      "sql",
      "swift",
      "toml",
      "typescript",
      "xml",
      "csv"
    ]
  },
  {
    "id": "asm",
    "scopeName": "source.asm.x86_64",
    "path": "asm.json"
  },
  {
    "id": "astro",
    "scopeName": "source.astro",
    "path": "astro.json",
    "embeddedLangs": [
      "javascript",
      "json",
      "typescript",
      "css",
      "less",
      "postcss",
      "sass",
      "scss",
      "stylus",
      "tsx"
    ]
  },
  {
    "id": "awk",
    "scopeName": "source.awk",
    "path": "awk.json"
  },
  {
    "id": "ballerina",
    "scopeName": "source.ballerina",
    "path": "ballerina.json"
  },
  {
    "id": "bat",
    "scopeName": "source.batchfile",
    "path": "bat.json",
    "aliases": [
      "batch"
    ]
  },
  {
    "id": "beancount",
    "scopeName": "text.beancount",
    "path": "beancount.json"
  },
  {
    "id": "berry",
    "scopeName": "source.berry",
    "path": "berry.json",
    "aliases": [
      "be"
    ]
  },
  {
    "id": "bibtex",
    "scopeName": "text.bibtex",
    "path": "bibtex.json"
  },
  {
    "id": "bicep",
    "scopeName": "source.bicep",
    "path": "bicep.json"
  },
  {
    "id": "blade",
    "scopeName": "text.html.php.blade",
    "path": "blade.json",
    "embeddedLangs": [
      "html",
      "xml",
      "sql",
      "javascript",
      "json",
      "css"
    ]
  },
  {
    "id": "c",
    "scopeName": "source.c",
    "path": "c.json"
  },
  {
    "id": "cadence",
    "scopeName": "source.cadence",
    "path": "cadence.json",
    "aliases": [
      "cdc"
    ]
  },
  {
    "id": "clarity",
    "scopeName": "source.clar",
    "path": "clarity.json"
  },
  {
    "id": "clojure",
    "scopeName": "source.clojure",
    "path": "clojure.json",
    "aliases": [
      "clj"
    ]
  },
  {
    "id": "cmake",
    "scopeName": "source.cmake",
    "path": "cmake.json"
  },
  {
    "id": "cobol",
    "scopeName": "source.cobol",
    "path": "cobol.json",
    "embeddedLangs": [
      "sql",
      "html",
      "java"
    ]
  },
  {
    "id": "codeowners",
    "scopeName": "text.codeowners",
    "path": "codeowners.json"
  },
  {
    "id": "codeql",
    "scopeName": "source.ql",
    "path": "codeql.json",
    "aliases": [
      "ql"
    ]
  },
  {
    "id": "coffee",
    "scopeName": "source.coffee",
    "path": "coffee.json",
    "embeddedLangs": [
      "javascript"
    ]
  },
  {
    "id": "common-lisp",
    "scopeName": "source.commonlisp",
    "path": "common-lisp.json"
  },
  {
    "id": "cpp",
    "scopeName": "source.cpp",
    "path": "cpp.json",
    "embeddedLangs": [
      "regexp",
      "glsl",
      "sql"
    ]
  },
  {
    "id": "crystal",
    "scopeName": "source.crystal",
    "path": "crystal.json",
    "embeddedLangs": [
      "html",
      "sql",
      "css",
      "c",
      "javascript",
      "shellscript"
    ]
  },
  {
    "id": "csharp",
    "scopeName": "source.cs",
    "path": "csharp.json",
    "aliases": [
      "c#",
      "cs"
    ]
  },
  {
    "id": "css",
    "scopeName": "source.css",
    "path": "css.json"
  },
  {
    "id": "csv",
    "scopeName": "text.csv",
    "path": "csv.json"
  },
  {
    "id": "cue",
    "scopeName": "source.cue",
    "path": "cue.json"
  },
  {
    "id": "cypher",
    "scopeName": "source.cypher",
    "path": "cypher.json"
  },
  {
    "id": "d",
    "scopeName": "source.d",
    "path": "d.json"
  },
  {
    "id": "dart",
    "scopeName": "source.dart",
    "path": "dart.json"
  },
  {
    "id": "dax",
    "scopeName": "source.dax",
    "path": "dax.json"
  },
  {
    "id": "desktop",
    "scopeName": "source.desktop",
    "path": "desktop.json"
  },
  {
    "id": "diff",
    "scopeName": "source.diff",
    "path": "diff.json"
  },
  {
    "id": "docker",
    "scopeName": "source.dockerfile",
    "path": "docker.json",
    "aliases": [
      "dockerfile"
    ]
  },
  {
    "id": "dream-maker",
    "scopeName": "source.dm",
    "path": "dream-maker.json"
  },
  {
    "id": "edge",
    "scopeName": "text.html.edge",
    "path": "edge.json",
    "embeddedLangs": [
      "html",
      "html-derivative",
      "typescript"
    ]
  },
  {
    "id": "elixir",
    "scopeName": "source.elixir",
    "path": "elixir.json",
    "embeddedLangs": [
      "html"
    ]
  },
  {
    "id": "elm",
    "scopeName": "source.elm",
    "path": "elm.json",
    "embeddedLangs": [
      "glsl"
    ]
  },
  {
    "id": "emacs-lisp",
    "scopeName": "source.emacs.lisp",
    "path": "emacs-lisp.json"
  },
  {
    "id": "erb",
    "scopeName": "text.html.erb",
    "path": "erb.json",
    "embeddedLangs": [
      "html",
      "ruby"
    ]
  },
  {
    "id": "erlang",
    "scopeName": "source.erlang",
    "path": "erlang.json",
    "aliases": [
      "erl"
    ]
  },
  {
    "id": "fennel",
    "scopeName": "source.fnl",
    "path": "fennel.json"
  },
  {
    "id": "fish",
    "scopeName": "source.fish",
    "path": "fish.json"
  },
  {
    "id": "fluent",
    "scopeName": "source.ftl",
    "path": "fluent.json"
  },
  {
    "id": "fortran-fixed-form",
    "scopeName": "source.fortran.fixed",
    "path": "fortran-fixed-form.json",
    "embeddedLangs": [
      "fortran-free-form"
    ]
  },
  {
    "id": "fortran-free-form",
    "scopeName": "source.fortran.free",
    "path": "fortran-free-form.json"
  },
  {
    "id": "fsharp",
    "scopeName": "source.fsharp",
    "path": "fsharp.json",
    "aliases": [
      "f#",
      "fs"
    ],
    "embeddedLangs": [
      "markdown"
    ]
  },
  {
    "id": "gdresource",
    "scopeName": "source.gdresource",
    "path": "gdresource.json",
    "embeddedLangs": [
      "gdscript",
      "gdshader"
    ]
  },
  {
    "id": "gdscript",
    "scopeName": "source.gdscript",
    "path": "gdscript.json"
  },
  {
    "id": "gdshader",
    "scopeName": "source.gdshader",
    "path": "gdshader.json"
  },
  {
    "id": "genie",
    "scopeName": "source.genie",
    "path": "genie.json"
  },
  {
    "id": "gherkin",
    "scopeName": "text.gherkin.feature",
    "path": "gherkin.json"
  },
  {
    "id": "git-commit",
    "scopeName": "text.git-commit",
    "path": "git-commit.json",
    "embeddedLangs": [
      "diff"
    ]
  },
  {
    "id": "git-rebase",
    "scopeName": "text.git-rebase",
    "path": "git-rebase.json",
    "embeddedLangs": [
      "shellscript"
    ]
  },
  {
    "id": "gleam",
    "scopeName": "source.gleam",
    "path": "gleam.json"
  },
  {
    "id": "glimmer-js",
    "scopeName": "source.gjs",
    "path": "glimmer-js.json",
    "embeddedLangs": [
      "javascript",
      "typescript",
      "html",
      "css"
    ]
  },
  {
    "id": "glimmer-ts",
    "scopeName": "source.gts",
    "path": "glimmer-ts.json",
    "embeddedLangs": [
      "typescript",
      "javascript",
      "html",
      "css"
    ]
  },
  {
    "id": "glsl",
    "scopeName": "source.glsl",
    "path": "glsl.json",
    "embeddedLangs": [
      "c"
    ]
  },
  {
    "id": "gnuplot",
    "scopeName": "source.gnuplot",
    "path": "gnuplot.json"
  },
  {
    "id": "go",
    "scopeName": "source.go",
    "path": "go.json"
  },
  {
    "id": "graphql",
    "scopeName": "source.graphql",
    "path": "graphql.json",
    "embeddedLangs": [
      "javascript",
      "typescript",
      "jsx",
      "tsx"
    ]
  },
  {
    "id": "groovy",
    "scopeName": "source.groovy",
    "path": "groovy.json"
  },
  {
    "id": "hack",
    "scopeName": "source.hack",
    "path": "hack.json",
    "embeddedLangs": [
      "html",
      "sql"
    ]
  },
  {
    "id": "haml",
    "scopeName": "text.haml",
    "path": "haml.json",
    "embeddedLangs": [
      "ruby",
      "javascript",
      "sass",
      "coffee",
      "markdown",
      "css"
    ]
  },
  {
    "id": "handlebars",
    "scopeName": "text.html.handlebars",
    "path": "handlebars.json",
    "aliases": [
      "hbs"
    ],
    "embeddedLangs": [
      "html",
      "css",
      "javascript",
      "yaml"
    ]
  },
  {
    "id": "haskell",
    "scopeName": "source.haskell",
    "path": "haskell.json",
    "aliases": [
      "hs"
    ]
  },
  {
    "id": "haxe",
    "scopeName": "source.hx",
    "path": "haxe.json"
  },
  {
    "id": "hcl",
    "scopeName": "source.hcl",
    "path": "hcl.json"
  },
  {
    "id": "hjson",
    "scopeName": "source.hjson",
    "path": "hjson.json"
  },
  {
    "id": "hlsl",
    "scopeName": "source.hlsl",
    "path": "hlsl.json"
  },
  {
    "id": "html-derivative",
    "scopeName": "text.html.derivative",
    "path": "html-derivative.json",
    "embeddedLangs": [
      "html"
    ]
  },
  {
    "id": "html",
    "scopeName": "text.html.basic",
    "path": "html.json",
    "embeddedLangs": [
      "javascript",
      "css"
    ]
  },
  {
    "id": "http",
    "scopeName": "source.http",
    "path": "http.json",
    "embeddedLangs": [
      "shellscript",
      "json",
      "xml",
      "graphql"
    ]
  },
  {
    "id": "hxml",
    "scopeName": "source.hxml",
    "path": "hxml.json",
    "embeddedLangs": [
      "haxe"
    ]
  },
  {
    "id": "hy",
    "scopeName": "source.hy",
    "path": "hy.json"
  },
  {
    "id": "imba",
    "scopeName": "source.imba",
    "path": "imba.json",
    "embeddedLangs": [
      "typescript"
    ]
  },
  {
    "id": "ini",
    "scopeName": "source.ini",
    "path": "ini.json",
    "aliases": [
      "properties"
    ]
  },
  {
    "id": "java",
    "scopeName": "source.java",
    "path": "java.json"
  },
  {
    "id": "javascript",
    "scopeName": "source.js",
    "path": "javascript.json",
    "aliases": [
      "js"
    ]
  },
  {
    "id": "jinja-html",
    "scopeName": "text.html.jinja",
    "path": "jinja-html.json",
    "embeddedLangs": [
      "html"
    ]
  },
  {
    "id": "jison",
    "scopeName": "source.jison",
    "path": "jison.json",
    "embeddedLangs": [
      "javascript"
    ]
  },
  {
    "id": "json",
    "scopeName": "source.json",
    "path": "json.json"
  },
  {
    "id": "json5",
    "scopeName": "source.json5",
    "path": "json5.json"
  },
  {
    "id": "jsonc",
    "scopeName": "source.json.comments",
    "path": "jsonc.json"
  },
  {
    "id": "jsonl",
    "scopeName": "source.json.lines",
    "path": "jsonl.json"
  },
  {
    "id": "jsonnet",
    "scopeName": "source.jsonnet",
    "path": "jsonnet.json"
  },
  {
    "id": "jssm",
    "scopeName": "source.jssm",
    "path": "jssm.json",
    "aliases": [
      "fsl"
    ]
  },
  {
    "id": "jsx",
    "scopeName": "source.js.jsx",
    "path": "jsx.json"
  },
  {
    "id": "julia",
    "scopeName": "source.julia",
    "path": "julia.json",
    "embeddedLangs": [
      "cpp",
      "python",
      "javascript",
      "r",
      "sql"
    ]
  },
  {
    "id": "kotlin",
    "scopeName": "source.kotlin",
    "path": "kotlin.json"
  },
  {
    "id": "kusto",
    "scopeName": "source.kusto",
    "path": "kusto.json",
    "aliases": [
      "kql"
    ]
  },
  {
    "id": "latex",
    "scopeName": "text.tex.latex",
    "path": "latex.json",
    "embeddedLangs": [
      "tex",
      "shellscript",
      "css",
      "gnuplot",
      "haskell",
      "html",
      "java",
      "julia",
      "javascript",
      "lua",
      "python",
      "ruby",
      "rust",
      "typescript",
      "xml",
      "yaml",
      "scala"
    ]
  },
  {
    "id": "lean",
    "scopeName": "source.lean4",
    "path": "lean.json"
  },
  {
    "id": "less",
    "scopeName": "source.css.less",
    "path": "less.json"
  },
  {
    "id": "liquid",
    "scopeName": "text.html.liquid",
    "path": "liquid.json",
    "embeddedLangs": [
      "html",
      "javascript",
      "json",
      "css"
    ]
  },
  {
    "id": "log",
    "scopeName": "text.log",
    "path": "log.json"
  },
  {
    "id": "logo",
    "scopeName": "source.logo",
    "path": "logo.json"
  },
  {
    "id": "lua",
    "scopeName": "source.lua",
    "path": "lua.json",
    "embeddedLangs": [
      "c"
    ]
  },
  {
    "id": "luau",
    "scopeName": "source.luau",
    "path": "luau.json"
  },
  {
    "id": "make",
    "scopeName": "source.makefile",
    "path": "make.json",
    "aliases": [
      "makefile"
    ]
  },
  {
    "id": "markdown-vue",
    "scopeName": "markdown.vue.codeblock",
    "path": "markdown-vue.json",
    "embeddedLangs": [
      "vue"
    ]
  },
  {
    "id": "markdown",
    "scopeName": "text.html.markdown",
    "path": "markdown.json",
    "aliases": [
      "md"
    ],
    "embeddedLangs": [
      "html-derivative",
      "html",
      "bibtex",
      "c",
      "clojure",
      "coffee",
      "cpp",
      "csharp",
      "css",
      "dart",
      "diff",
      "docker",
      "bat",
      "elixir",
      "erlang",
      "fsharp",
      "git-commit",
      "git-rebase",
      "go",
      "groovy",
      "handlebars",
      "ini",
      "java",
      "javascript",
      "json",
      "jsonc",
      "julia",
      "latex",
      "less",
      "log",
      "lua",
      "make",
      "objective-c",
      "perl",
      "raku",
      "php",
      "powershell",
      "pug",
      "python",
      "r",
      "regexp",
      "ruby",
      "rust",
      "scala",
      "scss",
      "shellscript",
      "sql",
      "swift",
      "typescript",
      "tsx",
      "vb",
      "xml",
      "xsl",
      "yaml"
    ]
  },
  {
    "id": "marko",
    "scopeName": "text.marko",
    "path": "marko.json",
    "embeddedLangs": [
      "css",
      "less",
      "scss",
      "javascript"
    ]
  },
  {
    "id": "matlab",
    "scopeName": "source.matlab",
    "path": "matlab.json"
  },
  {
    "id": "mdc",
    "scopeName": "text.markdown.mdc",
    "path": "mdc.json",
    "embeddedLangs": [
      "markdown",
      "yaml",
      "html-derivative"
    ]
  },
  {
    "id": "mdx",
    "scopeName": "source.mdx",
    "path": "mdx.json",
    "embeddedLangs": [
      "c",
      "clojure",
      "coffee",
      "cpp",
      "csharp",
      "css",
      "diff",
      "docker",
      "elixir",
      "elm",
      "erlang",
      "go",
      "graphql",
      "haskell",
      "html",
      "ini",
      "java",
      "javascript",
      "json",
      "julia",
      "kotlin",
      "less",
      "lua",
      "make",
      "markdown",
      "objective-c",
      "perl",
      "python",
      "r",
      "ruby",
      "rust",
      "scala",
      "scss",
      "shellscript",
      "shellsession",
      "sql",
      "xml",
      "swift",
      "toml",
      "typescript",
      "tsx",
      "yaml"
    ]
  },
  {
    "id": "mermaid",
    "scopeName": "markdown.mermaid.codeblock",
    "path": "mermaid.json"
  },
  {
    "id": "mojo",
    "scopeName": "source.mojo",
    "path": "mojo.json"
  },
  {
    "id": "move",
    "scopeName": "source.move",
    "path": "move.json"
  },
  {
    "id": "narrat",
    "scopeName": "source.narrat",
    "path": "narrat.json"
  },
  {
    "id": "nextflow",
    "scopeName": "source.nextflow",
    "path": "nextflow.json"
  },
  {
    "id": "nginx",
    "scopeName": "source.nginx",
    "path": "nginx.json",
    "embeddedLangs": [
      "lua"
    ]
  },
  {
    "id": "nim",
    "scopeName": "source.nim",
    "path": "nim.json",
    "embeddedLangs": [
      "c",
      "html",
      "xml",
      "javascript",
      "css",
      "glsl",
      "markdown"
    ]
  },
  {
    "id": "nix",
    "scopeName": "source.nix",
    "path": "nix.json"
  },
  {
    "id": "nushell",
    "scopeName": "source.nushell",
    "path": "nushell.json"
  },
  {
    "id": "objective-c",
    "scopeName": "source.objc",
    "path": "objective-c.json",
    "aliases": [
      "objc"
    ]
  },
  {
    "id": "objective-cpp",
    "scopeName": "source.objcpp",
    "path": "objective-cpp.json"
  },
  {
    "id": "ocaml",
    "scopeName": "source.ocaml",
    "path": "ocaml.json"
  },
  {
    "id": "pascal",
    "scopeName": "source.pascal",
    "path": "pascal.json"
  },
  {
    "id": "perl",
    "scopeName": "source.perl",
    "path": "perl.json",
    "embeddedLangs": [
      "html",
      "xml",
      "css",
      "javascript",
      "sql"
    ]
  },
  {
    "id": "php",
    "scopeName": "source.php",
    "path": "php.json",
    "embeddedLangs": [
      "html",
      "xml",
      "sql",
      "javascript",
      "json",
      "css"
    ]
  },
  {
    "id": "plsql",
    "scopeName": "source.plsql.oracle",
    "path": "plsql.json"
  },
  {
    "id": "po",
    "scopeName": "source.po",
    "path": "po.json"
  },
  {
    "id": "postcss",
    "scopeName": "source.css.postcss",
    "path": "postcss.json"
  },
  {
    "id": "powerquery",
    "scopeName": "source.powerquery",
    "path": "powerquery.json"
  },
  {
    "id": "powershell",
    "scopeName": "source.powershell",
    "path": "powershell.json",
    "aliases": [
      "ps",
      "ps1"
    ]
  },
  {
    "id": "prisma",
    "scopeName": "source.prisma",
    "path": "prisma.json"
  },
  {
    "id": "prolog",
    "scopeName": "source.prolog",
    "path": "prolog.json"
  },
  {
    "id": "proto",
    "scopeName": "source.proto",
    "path": "proto.json"
  },
  {
    "id": "pug",
    "scopeName": "text.pug",
    "path": "pug.json",
    "aliases": [
      "jade"
    ],
    "embeddedLangs": [
      "javascript",
      "css",
      "sass",
      "scss",
      "stylus",
      "coffee",
      "html"
    ]
  },
  {
    "id": "puppet",
    "scopeName": "source.puppet",
    "path": "puppet.json"
  },
  {
    "id": "purescript",
    "scopeName": "source.purescript",
    "path": "purescript.json"
  },
  {
    "id": "python",
    "scopeName": "source.python",
    "path": "python.json",
    "aliases": [
      "py"
    ]
  },
  {
    "id": "qml",
    "scopeName": "source.qml",
    "path": "qml.json",
    "embeddedLangs": [
      "javascript"
    ]
  },
  {
    "id": "qmldir",
    "scopeName": "source.qmldir",
    "path": "qmldir.json"
  },
  {
    "id": "qss",
    "scopeName": "source.qss",
    "path": "qss.json"
  },
  {
    "id": "r",
    "scopeName": "source.r",
    "path": "r.json"
  },
  {
    "id": "racket",
    "scopeName": "source.racket",
    "path": "racket.json"
  },
  {
    "id": "raku",
    "scopeName": "source.perl.6",
    "path": "raku.json",
    "aliases": [
      "perl6"
    ]
  },
  {
    "id": "razor",
    "scopeName": "text.aspnetcorerazor",
    "path": "razor.json",
    "embeddedLangs": [
      "html",
      "csharp"
    ]
  },
  {
    "id": "reg",
    "scopeName": "source.reg",
    "path": "reg.json"
  },
  {
    "id": "regexp",
    "scopeName": "source.regexp.python",
    "path": "regexp.json"
  },
  {
    "id": "rel",
    "scopeName": "source.rel",
    "path": "rel.json"
  },
  {
    "id": "riscv",
    "scopeName": "source.riscv",
    "path": "riscv.json"
  },
  {
    "id": "rst",
    "scopeName": "source.rst",
    "path": "rst.json",
    "embeddedLangs": [
      "cmake",
      "shellscript",
      "cpp",
      "javascript",
      "python",
      "ruby",
      "yaml",
      "html-derivative"
    ]
  },
  {
    "id": "ruby",
    "scopeName": "source.ruby",
    "path": "ruby.json",
    "aliases": [
      "rb"
    ],
    "embeddedLangs": [
      "html",
      "xml",
      "sql",
      "css",
      "c",
      "javascript",
      "shellscript",
      "lua"
    ]
  },
  {
    "id": "rust",
    "scopeName": "source.rust",
    "path": "rust.json",
    "aliases": [
      "rs"
    ]
  },
  {
    "id": "sas",
    "scopeName": "source.sas",
    "path": "sas.json",
    "embeddedLangs": [
      "sql"
    ]
  },
  {
    "id": "sass",
    "scopeName": "source.sass",
    "path": "sass.json"
  },
  {
    "id": "scala",
    "scopeName": "source.scala",
    "path": "scala.json"
  },
  {
    "id": "scheme",
    "scopeName": "source.scheme",
    "path": "scheme.json"
  },
  {
    "id": "scss",
    "scopeName": "source.css.scss",
    "path": "scss.json",
    "embeddedLangs": [
      "css"
    ]
  },
  {
    "id": "shaderlab",
    "scopeName": "source.shaderlab",
    "path": "shaderlab.json",
    "aliases": [
      "shader"
    ],
    "embeddedLangs": [
      "hlsl"
    ]
  },
  {
    "id": "shellscript",
    "scopeName": "source.shell",
    "path": "shellscript.json",
    "aliases": [
      "bash",
      "console",
      "sh",
      "shell",
      "zsh"
    ]
  },
  {
    "id": "shellsession",
    "scopeName": "text.shell-session",
    "path": "shellsession.json",
    "embeddedLangs": [
      "shellscript"
    ]
  },
  {
    "id": "smalltalk",
    "scopeName": "source.smalltalk",
    "path": "smalltalk.json"
  },
  {
    "id": "solidity",
    "scopeName": "source.solidity",
    "path": "solidity.json"
  },
  {
    "id": "soy",
    "scopeName": "text.html.soy",
    "path": "soy.json",
    "embeddedLangs": [
      "html"
    ]
  },
  {
    "id": "sparql",
    "scopeName": "source.sparql",
    "path": "sparql.json",
    "embeddedLangs": [
      "turtle"
    ]
  },
  {
    "id": "splunk",
    "scopeName": "source.splunk_search",
    "path": "splunk.json"
  },
  {
    "id": "sql",
    "scopeName": "source.sql",
    "path": "sql.json"
  },
  {
    "id": "ssh-config",
    "scopeName": "source.ssh-config",
    "path": "ssh-config.json"
  },
  {
    "id": "stata",
    "scopeName": "source.stata",
    "path": "stata.json",
    "embeddedLangs": [
      "sql"
    ]
  },
  {
    "id": "stylus",
    "scopeName": "source.stylus",
    "path": "stylus.json",
    "aliases": [
      "styl"
    ]
  },
  {
    "id": "svelte",
    "scopeName": "source.svelte",
    "path": "svelte.json",
    "embeddedLangs": [
      "javascript",
      "typescript",
      "coffee",
      "css",
      "less",
      "postcss",
      "sass",
      "scss",
      "stylus",
      "pug",
      "markdown"
    ]
  },
  {
    "id": "swift",
    "scopeName": "source.swift",
    "path": "swift.json"
  },
  {
    "id": "system-verilog",
    "scopeName": "source.systemverilog",
    "path": "system-verilog.json"
  },
  {
    "id": "systemd",
    "scopeName": "source.systemd",
    "path": "systemd.json"
  },
  {
    "id": "tasl",
    "scopeName": "source.tasl",
    "path": "tasl.json"
  },
  {
    "id": "tcl",
    "scopeName": "source.tcl",
    "path": "tcl.json"
  },
  {
    "id": "templ",
    "scopeName": "source.templ",
    "path": "templ.json",
    "embeddedLangs": [
      "go",
      "javascript",
      "css"
    ]
  },
  {
    "id": "terraform",
    "scopeName": "source.hcl.terraform",
    "path": "terraform.json"
  },
  {
    "id": "tex",
    "scopeName": "text.tex",
    "path": "tex.json",
    "embeddedLangs": [
      "r"
    ]
  },
  {
    "id": "toml",
    "scopeName": "source.toml",
    "path": "toml.json"
  },
  {
    "id": "tsv",
    "scopeName": "text.tsv",
    "path": "tsv.json"
  },
  {
    "id": "tsx",
    "scopeName": "source.tsx",
    "path": "tsx.json"
  },
  {
    "id": "turtle",
    "scopeName": "source.turtle",
    "path": "turtle.json"
  },
  {
    "id": "twig",
    "scopeName": "text.html.twig",
    "path": "twig.json",
    "embeddedLangs": [
      "css",
      "javascript",
      "scss",
      "php",
      "python",
      "ruby"
    ]
  },
  {
    "id": "typescript",
    "scopeName": "source.ts",
    "path": "typescript.json",
    "aliases": [
      "ts"
    ]
  },
  {
    "id": "typespec",
    "scopeName": "source.tsp",
    "path": "typespec.json"
  },
  {
    "id": "typst",
    "scopeName": "source.typst",
    "path": "typst.json"
  },
  {
    "id": "v",
    "scopeName": "source.v",
    "path": "v.json"
  },
  {
    "id": "vala",
    "scopeName": "source.vala",
    "path": "vala.json"
  },
  {
    "id": "vb",
    "scopeName": "source.asp.vb.net",
    "path": "vb.json",
    "aliases": [
      "cmd"
    ]
  },
  {
    "id": "verilog",
    "scopeName": "source.verilog",
    "path": "verilog.json"
  },
  {
    "id": "vhdl",
    "scopeName": "source.vhdl",
    "path": "vhdl.json"
  },
  {
    "id": "viml",
    "scopeName": "source.viml",
    "path": "viml.json",
    "aliases": [
      "vim",
      "vimscript"
    ]
  },
  {
    "id": "vue-directives",
    "scopeName": "vue.directives",
    "path": "vue-directives.json",
    "embeddedLangs": [
      "vue"
    ]
  },
  {
    "id": "vue-html",
    "scopeName": "text.html.vue-html",
    "path": "vue-html.json",
    "embeddedLangs": [
      "vue",
      "javascript"
    ]
  },
  {
    "id": "vue-interpolations",
    "scopeName": "vue.interpolations",
    "path": "vue-interpolations.json",
    "embeddedLangs": [
      "vue"
    ]
  },
  {
    "id": "vue-sfc-style-variable-injection",
    "scopeName": "vue.sfc.style.variable.injection",
    "path": "vue-sfc-style-variable-injection.json",
    "embeddedLangs": [
      "javascript"
    ]
  },
  {
    "id": "vue",
    "scopeName": "source.vue",
    "path": "vue.json",
    "embeddedLangs": [
      "html",
      "markdown",
      "pug",
      "stylus",
      "sass",
      "css",
      "scss",
      "less",
      "javascript",
      "typescript",
      "jsx",
      "tsx",
      "coffee",
      "json",
      "jsonc",
      "json5",
      "yaml",
      "toml",
      "graphql",
      "html-derivative"
    ]
  },
  {
    "id": "vyper",
    "scopeName": "source.vyper",
    "path": "vyper.json"
  },
  {
    "id": "wasm",
    "scopeName": "source.wat",
    "path": "wasm.json"
  },
  {
    "id": "wenyan",
    "scopeName": "source.wenyan",
    "path": "wenyan.json",
    "aliases": [
      "文言"
    ]
  },
  {
    "id": "wgsl",
    "scopeName": "source.wgsl",
    "path": "wgsl.json"
  },
  {
    "id": "wikitext",
    "scopeName": "source.wikitext",
    "path": "wikitext.json",
    "embeddedLangs": [
      "html",
      "json",
      "bat",
      "bibtex",
      "c",
      "clojure",
      "coffee",
      "cpp",
      "csharp",
      "css",
      "dart",
      "diff",
      "docker",
      "elixir",
      "erlang",
      "fsharp",
      "go",
      "groovy",
      "handlebars",
      "ini",
      "java",
      "javascript",
      "jsonc",
      "julia",
      "latex",
      "less",
      "lua",
      "make",
      "markdown",
      "objective-c",
      "perl",
      "raku",
      "php",
      "powershell",
      "pug",
      "python",
      "r",
      "ruby",
      "rust",
      "scala",
      "scss",
      "shellscript",
      "sql",
      "swift",
      "typescript",
      "vb",
      "xml",
      "xsl",
      "yaml"
    ]
  },
  {
    "id": "wolfram",
    "scopeName": "source.wolfram",
    "path": "wolfram.json"
  },
  {
    "id": "xml",
    "scopeName": "text.xml",
    "path": "xml.json",
    "embeddedLangs": [
      "java"
    ]
  },
  {
    "id": "xsl",
    "scopeName": "text.xml.xsl",
    "path": "xsl.json",
    "embeddedLangs": [
      "xml"
    ]
  },
  {
    "id": "yaml",
    "scopeName": "source.yaml",
    "path": "yaml.json",
    "aliases": [
      "yml"
    ]
  },
  {
    "id": "zenscript",
    "scopeName": "source.zenscript",
    "path": "zenscript.json"
  },
  {
    "id": "zig",
    "scopeName": "source.zig",
    "path": "zig.json"
  }
];