// generated by lib/utils/2.update-languages.mjs
export const languages = [
  {
    "id": "abap",
    "scopeName": "source.abap",
    "path": "abap.tmLanguage.json"
  },
  {
    "id": "actionscript-3",
    "scopeName": "source.actionscript.3",
    "path": "actionscript-3.tmLanguage.json"
  },
  {
    "id": "ada",
    "scopeName": "source.ada",
    "path": "ada.tmLanguage.json"
  },
  {
    "id": "apache",
    "scopeName": "source.apacheconf",
    "path": "apache.tmLanguage.json"
  },
  {
    "id": "apex",
    "scopeName": "source.apex",
    "path": "apex.tmLanguage.json"
  },
  {
    "id": "apl",
    "scopeName": "source.apl",
    "path": "apl.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "xml",
      "css",
      "javascript",
      "json"
    ]
  },
  {
    "id": "applescript",
    "scopeName": "source.applescript",
    "path": "applescript.tmLanguage.json"
  },
  {
    "id": "ara",
    "scopeName": "source.ara",
    "path": "ara.tmLanguage.json"
  },
  {
    "id": "asm",
    "scopeName": "source.asm.x86_64",
    "path": "asm.tmLanguage.json"
  },
  {
    "id": "astro",
    "scopeName": "source.astro",
    "path": "astro.tmLanguage.json",
    "embeddedLangs": [
      "json",
      "javascript",
      "typescript",
      "stylus",
      "sass",
      "css",
      "scss",
      "less",
      "postcss",
      "tsx"
    ]
  },
  {
    "id": "awk",
    "scopeName": "source.awk",
    "path": "awk.tmLanguage.json"
  },
  {
    "id": "ballerina",
    "scopeName": "source.ballerina",
    "path": "ballerina.tmLanguage.json"
  },
  {
    "id": "bat",
    "scopeName": "source.batchfile",
    "path": "bat.tmLanguage.json",
    "aliases": [
      "batch"
    ]
  },
  {
    "id": "berry",
    "scopeName": "source.berry",
    "path": "berry.tmLanguage.json",
    "aliases": [
      "be"
    ]
  },
  {
    "id": "bibtex",
    "scopeName": "text.bibtex",
    "path": "bibtex.tmLanguage.json"
  },
  {
    "id": "bicep",
    "scopeName": "source.bicep",
    "path": "bicep.tmLanguage.json"
  },
  {
    "id": "blade",
    "scopeName": "text.html.php.blade",
    "path": "blade.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "xml",
      "sql",
      "javascript",
      "json",
      "css"
    ]
  },
  {
    "id": "c",
    "scopeName": "source.c",
    "path": "c.tmLanguage.json"
  },
  {
    "id": "cadence",
    "scopeName": "source.cadence",
    "path": "cadence.tmLanguage.json",
    "aliases": [
      "cdc"
    ]
  },
  {
    "id": "clarity",
    "scopeName": "source.clar",
    "path": "clarity.tmLanguage.json"
  },
  {
    "id": "clojure",
    "scopeName": "source.clojure",
    "path": "clojure.tmLanguage.json",
    "aliases": [
      "clj"
    ]
  },
  {
    "id": "cmake",
    "scopeName": "source.cmake",
    "path": "cmake.tmLanguage.json"
  },
  {
    "id": "cobol",
    "scopeName": "source.cobol",
    "path": "cobol.tmLanguage.json",
    "embeddedLangs": [
      "sql",
      "html",
      "java"
    ]
  },
  {
    "id": "codeql",
    "scopeName": "source.ql",
    "path": "codeql.tmLanguage.json",
    "aliases": [
      "ql"
    ],
    "embeddedLangs": [
      "markdown"
    ]
  },
  {
    "id": "coffee",
    "scopeName": "source.coffee",
    "path": "coffee.tmLanguage.json",
    "embeddedLangs": [
      "javascript"
    ]
  },
  {
    "id": "cpp",
    "scopeName": "source.cpp",
    "path": "cpp.tmLanguage.json",
    "embeddedLangs": [
      "glsl",
      "sql"
    ]
  },
  {
    "id": "crystal",
    "scopeName": "source.crystal",
    "path": "crystal.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "sql",
      "css",
      "c",
      "javascript",
      "shellscript"
    ]
  },
  {
    "id": "csharp",
    "scopeName": "source.cs",
    "path": "csharp.tmLanguage.json",
    "aliases": [
      "c#",
      "cs"
    ]
  },
  {
    "id": "css",
    "scopeName": "source.css",
    "path": "css.tmLanguage.json"
  },
  {
    "id": "cue",
    "scopeName": "source.cue",
    "path": "cue.tmLanguage.json"
  },
  {
    "id": "d",
    "scopeName": "source.d",
    "path": "d.tmLanguage.json"
  },
  {
    "id": "dart",
    "scopeName": "source.dart",
    "path": "dart.tmLanguage.json"
  },
  {
    "id": "dax",
    "scopeName": "source.dax",
    "path": "dax.tmLanguage.json"
  },
  {
    "id": "diff",
    "scopeName": "source.diff",
    "path": "diff.tmLanguage.json"
  },
  {
    "id": "docker",
    "scopeName": "source.dockerfile",
    "path": "docker.tmLanguage.json",
    "aliases": [
      "dockerfile"
    ]
  },
  {
    "id": "dream-maker",
    "scopeName": "source.dm",
    "path": "dream-maker.tmLanguage.json"
  },
  {
    "id": "elixir",
    "scopeName": "source.elixir",
    "path": "elixir.tmLanguage.json",
    "embeddedLangs": [
      "html"
    ]
  },
  {
    "id": "elm",
    "scopeName": "source.elm",
    "path": "elm.tmLanguage.json",
    "embeddedLangs": [
      "glsl"
    ]
  },
  {
    "id": "erb",
    "scopeName": "text.html.erb",
    "path": "erb.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "ruby"
    ]
  },
  {
    "id": "erlang",
    "scopeName": "source.erlang",
    "path": "erlang.tmLanguage.json",
    "aliases": [
      "erl"
    ]
  },
  {
    "id": "fish",
    "scopeName": "source.fish",
    "path": "fish.tmLanguage.json"
  },
  {
    "id": "fsharp",
    "scopeName": "source.fsharp",
    "path": "fsharp.tmLanguage.json",
    "aliases": [
      "f#",
      "fs"
    ],
    "embeddedLangs": [
      "markdown"
    ]
  },
  {
    "id": "gherkin",
    "scopeName": "text.gherkin.feature",
    "path": "gherkin.tmLanguage.json"
  },
  {
    "id": "git-commit",
    "scopeName": "text.git-commit",
    "path": "git-commit.tmLanguage.json",
    "embeddedLangs": [
      "diff"
    ]
  },
  {
    "id": "git-rebase",
    "scopeName": "text.git-rebase",
    "path": "git-rebase.tmLanguage.json",
    "embeddedLangs": [
      "shellscript"
    ]
  },
  {
    "id": "glsl",
    "scopeName": "source.glsl",
    "path": "glsl.tmLanguage.json",
    "embeddedLangs": [
      "c"
    ]
  },
  {
    "id": "gnuplot",
    "scopeName": "source.gnuplot",
    "path": "gnuplot.tmLanguage.json"
  },
  {
    "id": "go",
    "scopeName": "source.go",
    "path": "go.tmLanguage.json"
  },
  {
    "id": "graphql",
    "scopeName": "source.graphql",
    "path": "graphql.tmLanguage.json",
    "embeddedLangs": [
      "javascript",
      "typescript",
      "jsx",
      "tsx"
    ]
  },
  {
    "id": "groovy",
    "scopeName": "source.groovy",
    "path": "groovy.tmLanguage.json"
  },
  {
    "id": "hack",
    "scopeName": "source.hack",
    "path": "hack.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "sql"
    ]
  },
  {
    "id": "haml",
    "scopeName": "text.haml",
    "path": "haml.tmLanguage.json",
    "embeddedLangs": [
      "ruby",
      "javascript",
      "sass",
      "coffee",
      "markdown",
      "css"
    ]
  },
  {
    "id": "handlebars",
    "scopeName": "text.html.handlebars",
    "path": "handlebars.tmLanguage.json",
    "aliases": [
      "hbs"
    ],
    "embeddedLangs": [
      "html",
      "css",
      "javascript",
      "yaml"
    ]
  },
  {
    "id": "haskell",
    "scopeName": "source.haskell",
    "path": "haskell.tmLanguage.json",
    "aliases": [
      "hs"
    ]
  },
  {
    "id": "hcl",
    "scopeName": "source.hcl",
    "path": "hcl.tmLanguage.json"
  },
  {
    "id": "hlsl",
    "scopeName": "source.hlsl",
    "path": "hlsl.tmLanguage.json"
  },
  {
    "id": "html",
    "scopeName": "text.html.basic",
    "path": "html.tmLanguage.json",
    "embeddedLangs": [
      "javascript",
      "css"
    ]
  },
  {
    "id": "http",
    "scopeName": "source.http",
    "path": "http.tmLanguage.json",
    "embeddedLangs": [
      "shellscript",
      "json",
      "xml",
      "graphql"
    ]
  },
  {
    "id": "imba",
    "scopeName": "source.imba",
    "path": "imba.tmLanguage.json"
  },
  {
    "id": "ini",
    "scopeName": "source.ini",
    "path": "ini.tmLanguage.json",
    "aliases": [
      "properties"
    ]
  },
  {
    "id": "java",
    "scopeName": "source.java",
    "path": "java.tmLanguage.json"
  },
  {
    "id": "javascript",
    "scopeName": "source.js",
    "path": "javascript.tmLanguage.json",
    "aliases": [
      "js"
    ]
  },
  {
    "id": "jinja-html",
    "scopeName": "text.html.jinja",
    "path": "jinja-html.tmLanguage.json",
    "embeddedLangs": [
      "html"
    ]
  },
  {
    "id": "jison",
    "scopeName": "source.jison",
    "path": "jison.tmLanguage.json",
    "embeddedLangs": [
      "javascript"
    ]
  },
  {
    "id": "json",
    "scopeName": "source.json",
    "path": "json.tmLanguage.json"
  },
  {
    "id": "json5",
    "scopeName": "source.json5",
    "path": "json5.tmLanguage.json"
  },
  {
    "id": "jsonc",
    "scopeName": "source.json.comments",
    "path": "jsonc.tmLanguage.json"
  },
  {
    "id": "jsonnet",
    "scopeName": "source.jsonnet",
    "path": "jsonnet.tmLanguage.json"
  },
  {
    "id": "jssm",
    "scopeName": "source.jssm",
    "path": "jssm.tmLanguage.json",
    "aliases": [
      "fsl"
    ]
  },
  {
    "id": "jsx",
    "scopeName": "source.js.jsx",
    "path": "jsx.tmLanguage.json"
  },
  {
    "id": "julia",
    "scopeName": "source.julia",
    "path": "julia.tmLanguage.json",
    "embeddedLangs": [
      "cpp",
      "python",
      "javascript",
      "r",
      "sql"
    ]
  },
  {
    "id": "kotlin",
    "scopeName": "source.kotlin",
    "path": "kotlin.tmLanguage.json"
  },
  {
    "id": "kusto",
    "scopeName": "source.kusto",
    "path": "kusto.tmLanguage.json",
    "aliases": [
      "kql"
    ]
  },
  {
    "id": "latex",
    "scopeName": "text.tex.latex",
    "path": "latex.tmLanguage.json",
    "embeddedLangs": [
      "tex",
      "css",
      "haskell",
      "html",
      "xml",
      "java",
      "lua",
      "julia",
      "ruby",
      "javascript",
      "typescript",
      "python",
      "yaml",
      "rust",
      "scala",
      "gnuplot"
    ]
  },
  {
    "id": "less",
    "scopeName": "source.css.less",
    "path": "less.tmLanguage.json",
    "embeddedLangs": [
      "css"
    ]
  },
  {
    "id": "liquid",
    "scopeName": "text.html.liquid",
    "path": "liquid.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "css",
      "json",
      "javascript"
    ]
  },
  {
    "id": "lisp",
    "scopeName": "source.lisp",
    "path": "lisp.tmLanguage.json"
  },
  {
    "id": "logo",
    "scopeName": "source.logo",
    "path": "logo.tmLanguage.json"
  },
  {
    "id": "lua",
    "scopeName": "source.lua",
    "path": "lua.tmLanguage.json",
    "embeddedLangs": [
      "c"
    ]
  },
  {
    "id": "make",
    "scopeName": "source.makefile",
    "path": "make.tmLanguage.json",
    "aliases": [
      "makefile"
    ]
  },
  {
    "id": "markdown",
    "scopeName": "text.html.markdown",
    "path": "markdown.tmLanguage.json",
    "aliases": [
      "md"
    ],
    "embeddedLangs": [
      "css",
      "html",
      "ini",
      "java",
      "lua",
      "make",
      "perl",
      "r",
      "ruby",
      "php",
      "sql",
      "vb",
      "xml",
      "xsl",
      "yaml",
      "bat",
      "clojure",
      "coffee",
      "c",
      "cpp",
      "diff",
      "docker",
      "git-commit",
      "git-rebase",
      "go",
      "groovy",
      "pug",
      "javascript",
      "json",
      "jsonc",
      "less",
      "objective-c",
      "swift",
      "scss",
      "raku",
      "powershell",
      "python",
      "julia",
      "rust",
      "scala",
      "shellscript",
      "typescript",
      "tsx",
      "csharp",
      "fsharp",
      "dart",
      "handlebars",
      "erlang",
      "elixir",
      "latex",
      "bibtex"
    ]
  },
  {
    "id": "marko",
    "scopeName": "text.marko",
    "path": "marko.tmLanguage.json",
    "embeddedLangs": [
      "css",
      "less",
      "scss",
      "typescript"
    ]
  },
  {
    "id": "matlab",
    "scopeName": "source.matlab",
    "path": "matlab.tmLanguage.json"
  },
  {
    "id": "mdx",
    "scopeName": "source.mdx",
    "path": "mdx.tmLanguage.json",
    "embeddedLangs": [
      "tsx",
      "toml",
      "yaml",
      "c",
      "cpp",
      "csharp",
      "css",
      "diff",
      "go",
      "graphql",
      "html",
      "ini",
      "java",
      "javascript",
      "json",
      "kotlin",
      "less",
      "lua",
      "make",
      "markdown",
      "objective-c",
      "perl",
      "python",
      "r",
      "ruby",
      "rust",
      "scss",
      "shellscript",
      "sql",
      "xml",
      "swift",
      "typescript"
    ]
  },
  {
    "id": "mermaid",
    "scopeName": "source.mermaid",
    "path": "mermaid.tmLanguage.json"
  },
  {
    "id": "nginx",
    "scopeName": "source.nginx",
    "path": "nginx.tmLanguage.json",
    "embeddedLangs": [
      "lua"
    ]
  },
  {
    "id": "nim",
    "scopeName": "source.nim",
    "path": "nim.tmLanguage.json",
    "embeddedLangs": [
      "c",
      "html",
      "xml",
      "javascript",
      "css",
      "glsl",
      "markdown"
    ]
  },
  {
    "id": "nix",
    "scopeName": "source.nix",
    "path": "nix.tmLanguage.json"
  },
  {
    "id": "objective-c",
    "scopeName": "source.objc",
    "path": "objective-c.tmLanguage.json",
    "aliases": [
      "objc"
    ]
  },
  {
    "id": "objective-cpp",
    "scopeName": "source.objcpp",
    "path": "objective-cpp.tmLanguage.json"
  },
  {
    "id": "ocaml",
    "scopeName": "source.ocaml",
    "path": "ocaml.tmLanguage.json"
  },
  {
    "id": "pascal",
    "scopeName": "source.pascal",
    "path": "pascal.tmLanguage.json"
  },
  {
    "id": "perl",
    "scopeName": "source.perl",
    "path": "perl.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "xml",
      "css",
      "javascript",
      "sql"
    ]
  },
  {
    "id": "php",
    "scopeName": "source.php",
    "path": "php.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "xml",
      "sql",
      "javascript",
      "json",
      "css"
    ]
  },
  {
    "id": "plsql",
    "scopeName": "source.plsql.oracle",
    "path": "plsql.tmLanguage.json"
  },
  {
    "id": "postcss",
    "scopeName": "source.css.postcss",
    "path": "postcss.tmLanguage.json"
  },
  {
    "id": "powerquery",
    "scopeName": "source.powerquery",
    "path": "powerquery.tmLanguage.json"
  },
  {
    "id": "powershell",
    "scopeName": "source.powershell",
    "path": "powershell.tmLanguage.json",
    "aliases": [
      "ps",
      "ps1"
    ]
  },
  {
    "id": "prisma",
    "scopeName": "source.prisma",
    "path": "prisma.tmLanguage.json"
  },
  {
    "id": "prolog",
    "scopeName": "source.prolog",
    "path": "prolog.tmLanguage.json"
  },
  {
    "id": "proto",
    "scopeName": "source.proto",
    "path": "proto.tmLanguage.json"
  },
  {
    "id": "pug",
    "scopeName": "text.pug",
    "path": "pug.tmLanguage.json",
    "aliases": [
      "jade"
    ],
    "embeddedLangs": [
      "javascript",
      "css",
      "sass",
      "scss",
      "stylus",
      "coffee",
      "html"
    ]
  },
  {
    "id": "puppet",
    "scopeName": "source.puppet",
    "path": "puppet.tmLanguage.json"
  },
  {
    "id": "purescript",
    "scopeName": "source.purescript",
    "path": "purescript.tmLanguage.json"
  },
  {
    "id": "python",
    "scopeName": "source.python",
    "path": "python.tmLanguage.json",
    "aliases": [
      "py"
    ]
  },
  {
    "id": "r",
    "scopeName": "source.r",
    "path": "r.tmLanguage.json"
  },
  {
    "id": "raku",
    "scopeName": "source.perl.6",
    "path": "raku.tmLanguage.json",
    "aliases": [
      "perl6"
    ]
  },
  {
    "id": "razor",
    "scopeName": "text.aspnetcorerazor",
    "path": "razor.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "csharp"
    ]
  },
  {
    "id": "rel",
    "scopeName": "source.rel",
    "path": "rel.tmLanguage.json"
  },
  {
    "id": "riscv",
    "scopeName": "source.riscv",
    "path": "riscv.tmLanguage.json"
  },
  {
    "id": "rst",
    "scopeName": "source.rst",
    "path": "rst.tmLanguage.json",
    "embeddedLangs": [
      "cpp",
      "python",
      "javascript",
      "shellscript",
      "yaml",
      "cmake",
      "ruby"
    ]
  },
  {
    "id": "ruby",
    "scopeName": "source.ruby",
    "path": "ruby.tmLanguage.json",
    "aliases": [
      "rb"
    ],
    "embeddedLangs": [
      "html",
      "xml",
      "sql",
      "css",
      "c",
      "javascript",
      "shellscript",
      "lua"
    ]
  },
  {
    "id": "rust",
    "scopeName": "source.rust",
    "path": "rust.tmLanguage.json",
    "aliases": [
      "rs"
    ]
  },
  {
    "id": "sas",
    "scopeName": "source.sas",
    "path": "sas.tmLanguage.json",
    "embeddedLangs": [
      "sql"
    ]
  },
  {
    "id": "sass",
    "scopeName": "source.sass",
    "path": "sass.tmLanguage.json"
  },
  {
    "id": "scala",
    "scopeName": "source.scala",
    "path": "scala.tmLanguage.json"
  },
  {
    "id": "scheme",
    "scopeName": "source.scheme",
    "path": "scheme.tmLanguage.json"
  },
  {
    "id": "scss",
    "scopeName": "source.css.scss",
    "path": "scss.tmLanguage.json",
    "embeddedLangs": [
      "css"
    ]
  },
  {
    "id": "shaderlab",
    "scopeName": "source.shaderlab",
    "path": "shaderlab.tmLanguage.json",
    "aliases": [
      "shader"
    ],
    "embeddedLangs": [
      "hlsl"
    ]
  },
  {
    "id": "shellscript",
    "scopeName": "source.shell",
    "path": "shellscript.tmLanguage.json",
    "aliases": [
      "bash",
      "console",
      "sh",
      "shell",
      "zsh"
    ]
  },
  {
    "id": "smalltalk",
    "scopeName": "source.smalltalk",
    "path": "smalltalk.tmLanguage.json"
  },
  {
    "id": "solidity",
    "scopeName": "source.solidity",
    "path": "solidity.tmLanguage.json"
  },
  {
    "id": "sparql",
    "scopeName": "source.sparql",
    "path": "sparql.tmLanguage.json",
    "embeddedLangs": [
      "turtle"
    ]
  },
  {
    "id": "sql",
    "scopeName": "source.sql",
    "path": "sql.tmLanguage.json"
  },
  {
    "id": "ssh-config",
    "scopeName": "source.ssh-config",
    "path": "ssh-config.tmLanguage.json"
  },
  {
    "id": "stata",
    "scopeName": "source.stata",
    "path": "stata.tmLanguage.json",
    "embeddedLangs": [
      "sql"
    ]
  },
  {
    "id": "stylus",
    "scopeName": "source.stylus",
    "path": "stylus.tmLanguage.json",
    "aliases": [
      "styl"
    ]
  },
  {
    "id": "svelte",
    "scopeName": "source.svelte",
    "path": "svelte.tmLanguage.json",
    "embeddedLangs": [
      "javascript",
      "typescript",
      "coffee",
      "stylus",
      "sass",
      "css",
      "scss",
      "less",
      "postcss",
      "pug",
      "markdown"
    ]
  },
  {
    "id": "swift",
    "scopeName": "source.swift",
    "path": "swift.tmLanguage.json"
  },
  {
    "id": "system-verilog",
    "scopeName": "source.systemverilog",
    "path": "system-verilog.tmLanguage.json"
  },
  {
    "id": "tasl",
    "scopeName": "source.tasl",
    "path": "tasl.tmLanguage.json"
  },
  {
    "id": "tcl",
    "scopeName": "source.tcl",
    "path": "tcl.tmLanguage.json"
  },
  {
    "id": "tex",
    "scopeName": "text.tex",
    "path": "tex.tmLanguage.json",
    "embeddedLangs": [
      "r"
    ]
  },
  {
    "id": "toml",
    "scopeName": "source.toml",
    "path": "toml.tmLanguage.json"
  },
  {
    "id": "tsx",
    "scopeName": "source.tsx",
    "path": "tsx.tmLanguage.json"
  },
  {
    "id": "turtle",
    "scopeName": "source.turtle",
    "path": "turtle.tmLanguage.json"
  },
  {
    "id": "twig",
    "scopeName": "text.html.twig",
    "path": "twig.tmLanguage.json",
    "embeddedLangs": [
      "css",
      "javascript",
      "php",
      "python",
      "ruby"
    ]
  },
  {
    "id": "typescript",
    "scopeName": "source.ts",
    "path": "typescript.tmLanguage.json",
    "aliases": [
      "ts"
    ]
  },
  {
    "id": "v",
    "scopeName": "source.v",
    "path": "v.tmLanguage.json"
  },
  {
    "id": "vb",
    "scopeName": "source.asp.vb.net",
    "path": "vb.tmLanguage.json",
    "aliases": [
      "cmd"
    ]
  },
  {
    "id": "verilog",
    "scopeName": "source.verilog",
    "path": "verilog.tmLanguage.json"
  },
  {
    "id": "vhdl",
    "scopeName": "source.vhdl",
    "path": "vhdl.tmLanguage.json"
  },
  {
    "id": "viml",
    "scopeName": "source.viml",
    "path": "viml.tmLanguage.json",
    "aliases": [
      "vim",
      "vimscript"
    ]
  },
  {
    "id": "vue-html",
    "scopeName": "text.html.vue-html",
    "path": "vue-html.tmLanguage.json",
    "embeddedLangs": [
      "vue",
      "javascript"
    ]
  },
  {
    "id": "vue",
    "scopeName": "source.vue",
    "path": "vue.tmLanguage.json",
    "embeddedLangs": [
      "html",
      "markdown",
      "pug",
      "stylus",
      "sass",
      "css",
      "scss",
      "less",
      "javascript",
      "typescript",
      "jsx",
      "tsx",
      "json",
      "jsonc",
      "json5",
      "yaml",
      "toml",
      "graphql"
    ]
  },
  {
    "id": "wasm",
    "scopeName": "source.wat",
    "path": "wasm.tmLanguage.json"
  },
  {
    "id": "wenyan",
    "scopeName": "source.wenyan",
    "path": "wenyan.tmLanguage.json",
    "aliases": [
      "文言"
    ]
  },
  {
    "id": "wgsl",
    "scopeName": "source.wgsl",
    "path": "wgsl.tmLanguage.json"
  },
  {
    "id": "xml",
    "scopeName": "text.xml",
    "path": "xml.tmLanguage.json",
    "embeddedLangs": [
      "java"
    ]
  },
  {
    "id": "xsl",
    "scopeName": "text.xml.xsl",
    "path": "xsl.tmLanguage.json",
    "embeddedLangs": [
      "xml"
    ]
  },
  {
    "id": "yaml",
    "scopeName": "source.yaml",
    "path": "yaml.tmLanguage.json",
    "aliases": [
      "yml"
    ]
  },
  {
    "id": "zenscript",
    "scopeName": "source.zenscript",
    "path": "zenscript.tmLanguage.json"
  }
];