import { NextResponse } from "next/server";

export const config = {
  runtime: "edge",
};

// api/grammars?lang=js&v=0.1.8
export default async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200 });
  }

  const url = new URL(req.url);
  const langId = url.searchParams.get("lang");
  const version = url.searchParams.get("v");
  console.log("fetching grammars", langId, version);

  try {
    const grammars = await getGrammars(langId, version);
    const res = NextResponse.json(grammars);
    res.headers.set("Cache-Control", "s-maxage=1, stale-while-revalidate");
    res.headers.set("Access-Control-Allow-Methods", "GET");
    res.headers.set("Access-Control-Allow-Origin", "*");
    return res;
  } catch (e) {
    console.log("error fetching grammars", e);
    return new Response(e.message, { status: 500 });
  }
};

async function getGrammars(langId, version) {
  const paths = idToPaths[langId];
  const grammars = await Promise.all(
    paths.map(async (path) => {
      const r = await fetch(
        `https://unpkg.com/@code-hike/lighter@${version}/grammars/${path}`
      );

      if (!r.ok) {
        throw new Error(
          `https://unpkg.com/@code-hike/lighter@${version}/grammars/${path} ${r.status} ${r.statusText}`
        );
      }

      const grammar = await r.json();
      // grammar.names = [language.id, ...(language.aliases || [])];
      // grammar.embeddedLangs = language.embeddedLangs || [];
      return grammar;
    })
  );
  return grammars;
}

// generated with `node utils/update-language-data.mjs`
const idToPaths = {
  abap: ["abap.tmLanguage.json"],
  "actionscript-3": ["actionscript-3.tmLanguage.json"],
  ada: ["ada.tmLanguage.json"],
  apache: ["apache.tmLanguage.json"],
  apex: ["apex.tmLanguage.json"],
  apl: [
    "apl.tmLanguage.json",
    "java.tmLanguage.json",
    "json.tmLanguage.json",
    "javascript.tmLanguage.json",
    "css.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  applescript: ["applescript.tmLanguage.json"],
  ara: ["ara.tmLanguage.json"],
  asm: ["asm.tmLanguage.json"],
  astro: [
    "astro.tmLanguage.json",
    "tsx.tmLanguage.json",
    "postcss.tmLanguage.json",
    "less.tmLanguage.json",
    "scss.tmLanguage.json",
    "css.tmLanguage.json",
    "sass.tmLanguage.json",
    "stylus.tmLanguage.json",
    "typescript.tmLanguage.json",
    "javascript.tmLanguage.json",
    "json.tmLanguage.json",
  ],
  awk: ["awk.tmLanguage.json"],
  ballerina: ["ballerina.tmLanguage.json"],
  bat: ["bat.tmLanguage.json"],
  berry: ["berry.tmLanguage.json"],
  bibtex: ["bibtex.tmLanguage.json"],
  bicep: ["bicep.tmLanguage.json"],
  blade: [
    "blade.tmLanguage.json",
    "java.tmLanguage.json",
    "css.tmLanguage.json",
    "json.tmLanguage.json",
    "javascript.tmLanguage.json",
    "sql.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  c: ["c.tmLanguage.json"],
  cadence: ["cadence.tmLanguage.json"],
  clarity: ["clarity.tmLanguage.json"],
  clojure: ["clojure.tmLanguage.json"],
  cmake: ["cmake.tmLanguage.json"],
  cobol: [
    "cobol.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
    "java.tmLanguage.json",
    "html.tmLanguage.json",
    "sql.tmLanguage.json",
  ],
  codeql: [
    "codeql.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "stylus.tmLanguage.json",
    "sass.tmLanguage.json",
    "glsl.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "fsharp.tmLanguage.json",
    "csharp.tmLanguage.json",
    "tsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "scss.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "less.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "javascript.tmLanguage.json",
    "pug.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "coffee.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "yaml.tmLanguage.json",
    "xsl.tmLanguage.json",
    "xml.tmLanguage.json",
    "vb.tmLanguage.json",
    "sql.tmLanguage.json",
    "php.tmLanguage.json",
    "ruby.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "lua.tmLanguage.json",
    "java.tmLanguage.json",
    "ini.tmLanguage.json",
    "html.tmLanguage.json",
    "css.tmLanguage.json",
    "markdown.tmLanguage.json",
  ],
  coffee: ["coffee.tmLanguage.json", "javascript.tmLanguage.json"],
  cpp: [
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "sql.tmLanguage.json",
    "glsl.tmLanguage.json",
  ],
  crystal: [
    "crystal.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "javascript.tmLanguage.json",
    "c.tmLanguage.json",
    "css.tmLanguage.json",
    "sql.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  csharp: ["csharp.tmLanguage.json"],
  css: ["css.tmLanguage.json"],
  cue: ["cue.tmLanguage.json"],
  d: ["d.tmLanguage.json"],
  dart: ["dart.tmLanguage.json"],
  dax: ["dax.tmLanguage.json"],
  diff: ["diff.tmLanguage.json"],
  docker: ["docker.tmLanguage.json"],
  "dream-maker": ["dream-maker.tmLanguage.json"],
  elixir: [
    "elixir.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  elm: ["elm.tmLanguage.json", "c.tmLanguage.json", "glsl.tmLanguage.json"],
  erb: [
    "erb.tmLanguage.json",
    "java.tmLanguage.json",
    "lua.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "c.tmLanguage.json",
    "sql.tmLanguage.json",
    "xml.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
    "ruby.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  erlang: ["erlang.tmLanguage.json"],
  fish: ["fish.tmLanguage.json"],
  fsharp: [
    "fsharp.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "stylus.tmLanguage.json",
    "sass.tmLanguage.json",
    "glsl.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "csharp.tmLanguage.json",
    "tsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "scss.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "less.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "javascript.tmLanguage.json",
    "pug.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "coffee.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "yaml.tmLanguage.json",
    "xsl.tmLanguage.json",
    "xml.tmLanguage.json",
    "vb.tmLanguage.json",
    "sql.tmLanguage.json",
    "php.tmLanguage.json",
    "ruby.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "lua.tmLanguage.json",
    "java.tmLanguage.json",
    "ini.tmLanguage.json",
    "html.tmLanguage.json",
    "css.tmLanguage.json",
    "markdown.tmLanguage.json",
  ],
  gherkin: ["gherkin.tmLanguage.json"],
  "git-commit": ["git-commit.tmLanguage.json", "diff.tmLanguage.json"],
  "git-rebase": ["git-rebase.tmLanguage.json", "shellscript.tmLanguage.json"],
  glsl: ["glsl.tmLanguage.json", "c.tmLanguage.json"],
  gnuplot: ["gnuplot.tmLanguage.json"],
  go: ["go.tmLanguage.json"],
  graphql: [
    "graphql.tmLanguage.json",
    "tsx.tmLanguage.json",
    "jsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "javascript.tmLanguage.json",
  ],
  groovy: ["groovy.tmLanguage.json"],
  hack: [
    "hack.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
    "sql.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  haml: [
    "haml.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "stylus.tmLanguage.json",
    "glsl.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "fsharp.tmLanguage.json",
    "csharp.tmLanguage.json",
    "tsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "scss.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "less.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "pug.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "yaml.tmLanguage.json",
    "xsl.tmLanguage.json",
    "vb.tmLanguage.json",
    "php.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "java.tmLanguage.json",
    "ini.tmLanguage.json",
    "lua.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "c.tmLanguage.json",
    "sql.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
    "css.tmLanguage.json",
    "markdown.tmLanguage.json",
    "coffee.tmLanguage.json",
    "sass.tmLanguage.json",
    "javascript.tmLanguage.json",
    "ruby.tmLanguage.json",
  ],
  handlebars: [
    "handlebars.tmLanguage.json",
    "yaml.tmLanguage.json",
    "javascript.tmLanguage.json",
    "css.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  haskell: ["haskell.tmLanguage.json"],
  hcl: ["hcl.tmLanguage.json"],
  hlsl: ["hlsl.tmLanguage.json"],
  html: [
    "html.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
  ],
  http: [
    "http.tmLanguage.json",
    "tsx.tmLanguage.json",
    "jsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "javascript.tmLanguage.json",
    "java.tmLanguage.json",
    "graphql.tmLanguage.json",
    "xml.tmLanguage.json",
    "json.tmLanguage.json",
    "shellscript.tmLanguage.json",
  ],
  imba: ["imba.tmLanguage.json"],
  ini: ["ini.tmLanguage.json"],
  java: ["java.tmLanguage.json"],
  javascript: ["javascript.tmLanguage.json"],
  "jinja-html": [
    "jinja-html.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  jison: ["jison.tmLanguage.json", "javascript.tmLanguage.json"],
  json: ["json.tmLanguage.json"],
  json5: ["json5.tmLanguage.json"],
  jsonc: ["jsonc.tmLanguage.json"],
  jsonnet: ["jsonnet.tmLanguage.json"],
  jssm: ["jssm.tmLanguage.json"],
  jsx: ["jsx.tmLanguage.json"],
  julia: [
    "julia.tmLanguage.json",
    "c.tmLanguage.json",
    "glsl.tmLanguage.json",
    "sql.tmLanguage.json",
    "r.tmLanguage.json",
    "javascript.tmLanguage.json",
    "python.tmLanguage.json",
    "cpp.tmLanguage.json",
  ],
  kotlin: ["kotlin.tmLanguage.json"],
  kusto: ["kusto.tmLanguage.json"],
  latex: [
    "latex.tmLanguage.json",
    "glsl.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "sql.tmLanguage.json",
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "r.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "yaml.tmLanguage.json",
    "python.tmLanguage.json",
    "typescript.tmLanguage.json",
    "javascript.tmLanguage.json",
    "ruby.tmLanguage.json",
    "julia.tmLanguage.json",
    "lua.tmLanguage.json",
    "java.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
    "haskell.tmLanguage.json",
    "css.tmLanguage.json",
    "tex.tmLanguage.json",
  ],
  less: ["less.tmLanguage.json", "css.tmLanguage.json"],
  liquid: [
    "liquid.tmLanguage.json",
    "javascript.tmLanguage.json",
    "json.tmLanguage.json",
    "css.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  lisp: ["lisp.tmLanguage.json"],
  logo: ["logo.tmLanguage.json"],
  lua: ["lua.tmLanguage.json", "c.tmLanguage.json"],
  make: ["make.tmLanguage.json"],
  markdown: [
    "markdown.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "stylus.tmLanguage.json",
    "sass.tmLanguage.json",
    "glsl.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "fsharp.tmLanguage.json",
    "csharp.tmLanguage.json",
    "tsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "scss.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "less.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "javascript.tmLanguage.json",
    "pug.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "coffee.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "yaml.tmLanguage.json",
    "xsl.tmLanguage.json",
    "xml.tmLanguage.json",
    "vb.tmLanguage.json",
    "sql.tmLanguage.json",
    "php.tmLanguage.json",
    "ruby.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "lua.tmLanguage.json",
    "java.tmLanguage.json",
    "ini.tmLanguage.json",
    "html.tmLanguage.json",
    "css.tmLanguage.json",
    "applescript.tmLanguage.json",
  ],
  marko: [
    "marko.tmLanguage.json",
    "typescript.tmLanguage.json",
    "scss.tmLanguage.json",
    "less.tmLanguage.json",
    "css.tmLanguage.json",
  ],
  matlab: ["matlab.tmLanguage.json"],
  mdx: [
    "mdx.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "stylus.tmLanguage.json",
    "sass.tmLanguage.json",
    "glsl.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "fsharp.tmLanguage.json",
    "csharp.tmLanguage.json",
    "tsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "scss.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "less.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "javascript.tmLanguage.json",
    "pug.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "coffee.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "yaml.tmLanguage.json",
    "xsl.tmLanguage.json",
    "xml.tmLanguage.json",
    "vb.tmLanguage.json",
    "sql.tmLanguage.json",
    "php.tmLanguage.json",
    "ruby.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "lua.tmLanguage.json",
    "java.tmLanguage.json",
    "ini.tmLanguage.json",
    "html.tmLanguage.json",
    "css.tmLanguage.json",
    "markdown.tmLanguage.json",
    "jsx.tmLanguage.json",
    "applescript.tmLanguage.json",
  ],
  mermaid: ["mermaid.tmLanguage.json"],
  nginx: ["nginx.tmLanguage.json", "c.tmLanguage.json", "lua.tmLanguage.json"],
  nim: [
    "nim.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "stylus.tmLanguage.json",
    "sass.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "fsharp.tmLanguage.json",
    "csharp.tmLanguage.json",
    "tsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "scss.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "less.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "pug.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "coffee.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "yaml.tmLanguage.json",
    "xsl.tmLanguage.json",
    "vb.tmLanguage.json",
    "sql.tmLanguage.json",
    "php.tmLanguage.json",
    "ruby.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "lua.tmLanguage.json",
    "ini.tmLanguage.json",
    "java.tmLanguage.json",
    "markdown.tmLanguage.json",
    "glsl.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
    "c.tmLanguage.json",
  ],
  nix: ["nix.tmLanguage.json"],
  "objective-c": ["objective-c.tmLanguage.json"],
  "objective-cpp": ["objective-cpp.tmLanguage.json"],
  ocaml: ["ocaml.tmLanguage.json"],
  pascal: ["pascal.tmLanguage.json"],
  perl: [
    "perl.tmLanguage.json",
    "java.tmLanguage.json",
    "sql.tmLanguage.json",
    "javascript.tmLanguage.json",
    "css.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  php: [
    "php.tmLanguage.json",
    "java.tmLanguage.json",
    "css.tmLanguage.json",
    "json.tmLanguage.json",
    "javascript.tmLanguage.json",
    "sql.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  plsql: ["plsql.tmLanguage.json"],
  postcss: ["postcss.tmLanguage.json"],
  powerquery: ["powerquery.tmLanguage.json"],
  powershell: ["powershell.tmLanguage.json"],
  prisma: ["prisma.tmLanguage.json"],
  prolog: ["prolog.tmLanguage.json"],
  proto: ["proto.tmLanguage.json"],
  pug: [
    "pug.tmLanguage.json",
    "html.tmLanguage.json",
    "coffee.tmLanguage.json",
    "stylus.tmLanguage.json",
    "scss.tmLanguage.json",
    "sass.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
  ],
  puppet: ["puppet.tmLanguage.json"],
  purescript: ["purescript.tmLanguage.json"],
  python: ["python.tmLanguage.json"],
  r: ["r.tmLanguage.json"],
  raku: ["raku.tmLanguage.json"],
  razor: [
    "razor.tmLanguage.json",
    "css.tmLanguage.json",
    "javascript.tmLanguage.json",
    "csharp.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  rel: ["rel.tmLanguage.json"],
  riscv: ["riscv.tmLanguage.json"],
  rst: [
    "rst.tmLanguage.json",
    "java.tmLanguage.json",
    "lua.tmLanguage.json",
    "c.tmLanguage.json",
    "css.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
    "sql.tmLanguage.json",
    "glsl.tmLanguage.json",
    "ruby.tmLanguage.json",
    "cmake.tmLanguage.json",
    "yaml.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "javascript.tmLanguage.json",
    "python.tmLanguage.json",
    "cpp.tmLanguage.json",
  ],
  ruby: [
    "ruby.tmLanguage.json",
    "java.tmLanguage.json",
    "lua.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "javascript.tmLanguage.json",
    "c.tmLanguage.json",
    "css.tmLanguage.json",
    "sql.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  rust: ["rust.tmLanguage.json"],
  sas: ["sas.tmLanguage.json", "sql.tmLanguage.json"],
  sass: ["sass.tmLanguage.json"],
  scala: ["scala.tmLanguage.json"],
  scheme: ["scheme.tmLanguage.json"],
  scss: ["scss.tmLanguage.json", "css.tmLanguage.json"],
  shaderlab: ["shaderlab.tmLanguage.json", "hlsl.tmLanguage.json"],
  shellscript: ["shellscript.tmLanguage.json"],
  smalltalk: ["smalltalk.tmLanguage.json"],
  solidity: ["solidity.tmLanguage.json"],
  sparql: ["sparql.tmLanguage.json", "turtle.tmLanguage.json"],
  sql: ["sql.tmLanguage.json"],
  "ssh-config": ["ssh-config.tmLanguage.json"],
  stata: ["stata.tmLanguage.json", "sql.tmLanguage.json"],
  stylus: ["stylus.tmLanguage.json"],
  svelte: [
    "svelte.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "glsl.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "fsharp.tmLanguage.json",
    "csharp.tmLanguage.json",
    "tsx.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "yaml.tmLanguage.json",
    "xsl.tmLanguage.json",
    "xml.tmLanguage.json",
    "vb.tmLanguage.json",
    "sql.tmLanguage.json",
    "php.tmLanguage.json",
    "ruby.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "lua.tmLanguage.json",
    "java.tmLanguage.json",
    "ini.tmLanguage.json",
    "html.tmLanguage.json",
    "markdown.tmLanguage.json",
    "pug.tmLanguage.json",
    "postcss.tmLanguage.json",
    "less.tmLanguage.json",
    "scss.tmLanguage.json",
    "css.tmLanguage.json",
    "sass.tmLanguage.json",
    "stylus.tmLanguage.json",
    "coffee.tmLanguage.json",
    "typescript.tmLanguage.json",
    "javascript.tmLanguage.json",
  ],
  swift: ["swift.tmLanguage.json"],
  "system-verilog": ["system-verilog.tmLanguage.json"],
  tasl: ["tasl.tmLanguage.json"],
  tcl: ["tcl.tmLanguage.json"],
  tex: ["tex.tmLanguage.json", "r.tmLanguage.json"],
  toml: ["toml.tmLanguage.json"],
  tsx: ["tsx.tmLanguage.json"],
  turtle: ["turtle.tmLanguage.json"],
  twig: [
    "twig.tmLanguage.json",
    "java.tmLanguage.json",
    "lua.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "c.tmLanguage.json",
    "json.tmLanguage.json",
    "sql.tmLanguage.json",
    "xml.tmLanguage.json",
    "html.tmLanguage.json",
    "ruby.tmLanguage.json",
    "python.tmLanguage.json",
    "php.tmLanguage.json",
    "javascript.tmLanguage.json",
    "css.tmLanguage.json",
  ],
  typescript: ["typescript.tmLanguage.json"],
  v: ["v.tmLanguage.json"],
  vb: ["vb.tmLanguage.json"],
  verilog: ["verilog.tmLanguage.json"],
  vhdl: ["vhdl.tmLanguage.json"],
  viml: ["viml.tmLanguage.json"],
  "vue-html": [
    "vue-html.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "glsl.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "fsharp.tmLanguage.json",
    "csharp.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "coffee.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "xsl.tmLanguage.json",
    "xml.tmLanguage.json",
    "vb.tmLanguage.json",
    "sql.tmLanguage.json",
    "php.tmLanguage.json",
    "ruby.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "lua.tmLanguage.json",
    "java.tmLanguage.json",
    "ini.tmLanguage.json",
    "graphql.tmLanguage.json",
    "toml.tmLanguage.json",
    "yaml.tmLanguage.json",
    "json5.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "tsx.tmLanguage.json",
    "jsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "less.tmLanguage.json",
    "scss.tmLanguage.json",
    "css.tmLanguage.json",
    "sass.tmLanguage.json",
    "stylus.tmLanguage.json",
    "pug.tmLanguage.json",
    "markdown.tmLanguage.json",
    "html.tmLanguage.json",
    "javascript.tmLanguage.json",
    "vue.tmLanguage.json",
  ],
  vue: [
    "vue.tmLanguage.json",
    "gnuplot.tmLanguage.json",
    "haskell.tmLanguage.json",
    "tex.tmLanguage.json",
    "glsl.tmLanguage.json",
    "bibtex.tmLanguage.json",
    "latex.tmLanguage.json",
    "elixir.tmLanguage.json",
    "erlang.tmLanguage.json",
    "handlebars.tmLanguage.json",
    "dart.tmLanguage.json",
    "fsharp.tmLanguage.json",
    "csharp.tmLanguage.json",
    "shellscript.tmLanguage.json",
    "scala.tmLanguage.json",
    "rust.tmLanguage.json",
    "julia.tmLanguage.json",
    "python.tmLanguage.json",
    "powershell.tmLanguage.json",
    "raku.tmLanguage.json",
    "swift.tmLanguage.json",
    "objective-c.tmLanguage.json",
    "groovy.tmLanguage.json",
    "go.tmLanguage.json",
    "git-rebase.tmLanguage.json",
    "git-commit.tmLanguage.json",
    "docker.tmLanguage.json",
    "diff.tmLanguage.json",
    "cpp.tmLanguage.json",
    "c.tmLanguage.json",
    "coffee.tmLanguage.json",
    "clojure.tmLanguage.json",
    "bat.tmLanguage.json",
    "xsl.tmLanguage.json",
    "xml.tmLanguage.json",
    "vb.tmLanguage.json",
    "sql.tmLanguage.json",
    "php.tmLanguage.json",
    "ruby.tmLanguage.json",
    "r.tmLanguage.json",
    "perl.tmLanguage.json",
    "make.tmLanguage.json",
    "lua.tmLanguage.json",
    "java.tmLanguage.json",
    "ini.tmLanguage.json",
    "graphql.tmLanguage.json",
    "toml.tmLanguage.json",
    "yaml.tmLanguage.json",
    "json5.tmLanguage.json",
    "jsonc.tmLanguage.json",
    "json.tmLanguage.json",
    "tsx.tmLanguage.json",
    "jsx.tmLanguage.json",
    "typescript.tmLanguage.json",
    "javascript.tmLanguage.json",
    "less.tmLanguage.json",
    "scss.tmLanguage.json",
    "css.tmLanguage.json",
    "sass.tmLanguage.json",
    "stylus.tmLanguage.json",
    "pug.tmLanguage.json",
    "markdown.tmLanguage.json",
    "html.tmLanguage.json",
  ],
  wasm: ["wasm.tmLanguage.json"],
  wenyan: ["wenyan.tmLanguage.json"],
  wgsl: ["wgsl.tmLanguage.json"],
  xml: ["xml.tmLanguage.json", "java.tmLanguage.json"],
  xsl: ["xsl.tmLanguage.json", "java.tmLanguage.json", "xml.tmLanguage.json"],
  yaml: ["yaml.tmLanguage.json"],
  zenscript: ["zenscript.tmLanguage.json"],
};
